//
//  Icon.swift
//  Montage
//
//  Created by Eunyeong Kim on 2021/04/20.
//

import Foundation

/// Montage 번들 내에 포함된 아이콘들의 이름들입니다.
public enum Icon: String, CaseIterable {
    case add
    case addFill
    case apps
    case arrowDown
    case arrowLeft
    case arrowRight
    case arrowUp
    case bell
    case bellFill
    case bellPlus
    case blank
    case block
    case book
    case bookFill
    case bookmark
    case bookmarkFill
    case bubble
    case bubbleFill
    case businessBag
    case businessBagFill
    case calendar
    case camera
    case cameraFill
    case caretDown
    case caretUp
    case change
    case check
    case checkThick
    case chevronDown
    case chevronDownSmall
    case chevronDownThick
    case chevronDownThickSmall
    case chevronLeft
    case chevronLeftSmall
    case chevronLeftThick
    case chevronLeftThickSmall
    case chevronLeftTight
    case chevronLeftTightSmall
    case chevronLeftTightThick
    case chevronLeftTightThickSmall
    case chevronRight
    case chevronRightSmall
    case chevronRightThick
    case chevronRightThickSmall
    case chevronRightTight
    case chevronRightTightSmall
    case chevronRightTightThick
    case chevronRightTightThickSmall
    case chevronUp
    case chevronUpSmall
    case chevronUpThick
    case chevronUpThickSmall
    case circle
    case circleCheck
    case circleCheckFill
    case circleClose
    case circleExclamation
    case circleExclamationFill
    case circleFill
    case circleInfo
    case circleInfoFill
    case circlePlus
    case circlePlusFill
    case circlePoint
    case circleQuestion
    case circleQuestionFill
    case close
    case closeThick
    case coins
    case coinsFill
    case company
    case compass
    case compassFill
    case copy
    case document
    case documentPerson
    case documentPersonFill
    case dot
    case download
    case exclamation
    case externalLink
    case faceSmile
    case faceSmileFill
    case filter
    case filterFill
    case full
    case globe
    case handle
    case heart
    case heartFill
    case history
    case home
    case homeFill
    case image
    case keyboard
    case like
    case likeFill
    case lineHorizontal
    case lineHorizontalThick
    case link
    case list
    case listCategory
    case location
    case locationFill
    case lock
    case lockFill
    case lockOpen
    case lockOpenFill
    case logoApple
    case logoFacebook
    case logoGooglePlay
    case logoInstagram
    case logoLinkedIn
    case logoNaverBlog
    case logoYoutube
    case mail
    case menu
    case menuStar
    case menuThick
    case message
    case messageFill
    case moreHorizontal
    case moreVertical
    case moreVerticalTight
    case navigationCareer
    case navigationMenu
    case navigationMypage
    case navigationRecruit
    case navigationSocial
    case pause
    case pencil
    case pencilFill
    case person
    case personFill
    case personPlus
    case personPlusFill
    case persons
    case personsFill
    case pin
    case pinFill
    case play
    case plus
    case plusThick
    case question
    case refresh
    case search
    case searchThick
    case send
    case sendFill
    case setting
    case share
    case shareIos
    case squareHan
    case squareHangul
    case squareKana
    case squareLatin
    case squareMore
    case star
    case starFill
    case template
    case templateFill
    case thumbnail
    case thunder
    case thunderFill
    case trash
    case triangleExclamation
    case triangleExclamationFill
    case tune
    case upload
    case verifiedCheck
    case verifiedCheckFill
    case verifiedStar
    case verifiedStarFill
    case view
    case viewFill
    case viewSlash
    case viewSlashFill
    
    public var name: String { rawValue }
}
