//
//  Icon.swift
//  Montage
//
//  Created by Eunyeong Kim on 2021/04/20.
//

import Foundation

/// Montage 번들 내에 포함된 아이콘들의 이름들입니다.
public enum Icon: String, CaseIterable {
    case android
    case apps
    case arrowDown
    case arrowLeft
    case arrowRight
    case arrowUp
    case bell
    case bellFill
    case bellPlus
    case blank
    case book
    case bookFill
    case bookmark
    case bookmarkFill
    case bubble
    case bubbleFill
    case bubblePlus
    case bubblePlusFill
    case businessBag
    case businessBagFill
    case calendar
    case camera
    case cameraFill
    case caretDown
    case caretUp
    case change
    case check
    case checkThick
    case chevronDoubleLeft
    case chevronDoubleLeftSmall
    case chevronDoubleLeftThick
    case chevronDoubleLeftThickSmall
    case chevronDoubleRight
    case chevronDoubleRightSmall
    case chevronDoubleRightThick
    case chevronDoubleRightThickSmall
    case chevronDown
    case chevronDownSmall
    case chevronDownThick
    case chevronDownThickSmall
    case chevronLeft
    case chevronLeftSmall
    case chevronLeftThick
    case chevronLeftThickSmall
    case chevronLeftTight
    case chevronLeftTightSmall
    case chevronLeftTightThick
    case chevronLeftTightThickSmall
    case chevronRight
    case chevronRightSmall
    case chevronRightThick
    case chevronRightThickSmall
    case chevronRightTight
    case chevronRightTightSmall
    case chevronRightTightThick
    case chevronRightTightThickSmall
    case chevronUp
    case chevronUpSmall
    case chevronUpThick
    case chevronUpThickSmall
    case circle
    case circleBlock
    case circleCheck
    case circleCheckFill
    case circleClose
    case circleExclamation
    case circleExclamationFill
    case circleFill
    case circleInfo
    case circleInfoFill
    case circlePlus
    case circlePlusFill
    case circlePoint
    case circleQuestion
    case circleQuestionFill
    case close
    case closeThick
    case coins
    case coinsFill
    case company
    case companyCheck
    case companyCheckFill
    case companyFill
    case companyPlus
    case companyPlusFill
    case compass
    case compassFill
    case copy
    case crown
    case crownFill
    case desktop
    case desktopFill
    case document
    case documentFill
    case documentPerson
    case documentPersonFill
    case documentText
    case documentTextFill
    case dot
    case download
    case exclamation
    case externalLink
    case eye
    case eyeFill
    case eyeSlash
    case eyeSlashFill
    case faceSmile
    case faceSmileFill
    case filter
    case filterFill
    case folder
    case folderFill
    case folderJob
    case folderJobFill
    case folderStar
    case folderStarFill
    case full
    case globe
    case graduation
    case handle
    case heart
    case heartFill
    case history
    case home
    case homeFill
    case image
    case keyboard
    case like
    case likeFill
    case lineHorizontal
    case lineHorizontalThick
    case link
    case list
    case listCategory
    case location
    case locationFill
    case lock
    case lockFill
    case lockOpen
    case lockOpenFill
    case logoApple
    case logoFacebook
    case logoGooglePlay
    case logoInstagram
    case logoKakao
    case logoLinkedIn
    case logoNaverBlog
    case logoYoutube
    case magicWand
    case mail
    case menu
    case menuThick
    case message
    case messageFill
    case minus
    case minusThick
    case mobile
    case mobileFill
    case moreHorizontal
    case moreVertical
    case moreVerticalTight
    case navigationCareer
    case navigationMenu
    case navigationMypage
    case navigationRecruit
    case navigationSocial
    case pause
    case pencil
    case pencilFill
    case person
    case personFill
    case personPlus
    case personPlusFill
    case persons
    case personsFill
    case pin
    case pinFill
    case play
    case plus
    case plusThick
    case question
    case refresh
    case search
    case searchThick
    case send
    case sendFill
    case setting
    case share
    case shareIos
    case square
    case squareFill
    case squareHan
    case squareHangul
    case squareKana
    case squareLatin
    case squareMore
    case squarePlus
    case squarePlusFill
    case star
    case starFill
    case template
    case templateFill
    case thumbnail
    case thunder
    case thunderFill
    case trash
    case triangle
    case triangleExclamation
    case triangleExclamationFill
    case triangleFill
    case trophy
    case trophyFill
    case tune
    case upload
    case verifiedCheck
    case verifiedCheckFill
    case verifiedStar
    case verifiedStarFill
    case write
    
    public var name: String { rawValue }
}
