//
//  Icon.swift
//  Montage
//
//  Created by Eunyeong Kim on 2021/04/20.
//

import Foundation

public extension DesignSystem {
    enum Icon: String {
        // 12x12
        case fillBookmark12
        case fillCheckbox12
        case fillFilter12
        case fillHeart12
        case fillHome12
        case fillLike12
        case fillLock12
        case fillProfile12
        case fillRadio12
        case fillSend12
        case fillStar12
        case fillThunder12

        case lineCheckbox12
        case lineFilter12
        case lineHeart12
        case lineHome12
        case lineLike12
        case lineAlarmSetting12
        case lineAnswer12
        case lineArrowDown12
        case lineArrowLeft12
        case lineArrowRight12
        case lineArrowUp12
        case lineCheck12
        case lineDownload12
        case lineEmail12
        case lineExit12
        case lineExpand12
        case lineFold12
        case lineFull12
        case lineHandle12
        case lineLang12
        case lineLink12
        case lineMappin12
        case lineMenu12
        case lineMenuStar12
        case lineMore12
        case lineMoreVertical12
        case lineNotification12
        case linePin12
        case linePlus12
        case lineQuestion12
        case lineRefresh12
        case lineSetting12
        case lineShare12
        case lineShareLink12
        case lineStop12
        case lineToTop12
        case lineTrash12
        case lineUpload12
        case lineLock12
        case lineProfile12
        case lineRadio12
        case lineSend12
        case lineStar12
        case lineThunder12

        // 18x18
        case fillBag18
        case fillBookmark18
        case fillBoxCheck18
        case fillCamera18
        case fillCheckBadge18
        case fillCircleCheck18
        case fillCommunity18
        case fillConversation18
        case fillFiltering18
        case fillHeart18
        case fillHome18
        case fillLike18
        case fillLock18
        case fillMessege18
        case fillProfile18
        case fillRadio18
        case fillSearch18
        case fillSend18
        case fillStar18
        case fillStarBadge18
        case fillThunder18

        case lineAlramSetting18
        case lineAnswer18
        case lineArrowDown18
        case lineArrowLeft18
        case lineArrowRight18
        case lineArrowUp18
        case lineBag18
        case lineBookmark18
        case lineBoxCheck18
        case lineCalendar18
        case lineCamera18
        case lineCheck18
        case lineCheckBadge18
        case lineCircleAlert18
        case lineCircleCheck18
        case lineCircleHelp18
        case lineCircleInfo18
        case lineCirclePlus18
        case lineCommunity18
        case lineConversation18
        case lineDocument18
        case lineDownload18
        case lineEmail18
        case lineExit18
        case lineExpand18
        case lineFilter18
        case lineFiltering18
        case lineFold18
        case lineFull18
        case lineHandle18
        case lineHeart18
        case lineHome18
        case lineImage18
        case lineLang18
        case lineLangChn18
        case lineLangEng18
        case lineLangJpn18
        case lineLangKor18
        case lineLangMore18
        case lineLike18
        case lineLink18
        case lineLock18
        case lineMappin18
        case lineMenu18
        case lineMenuStar18
        case lineMessege18
        case lineMore18
        case lineMoreVertical18
        case lineNewtab18
        case lineNotification18
        case linePin18
        case linePlus18
        case lineProfile18
        case lineQuestion18
        case lineRadio18
        case lineRefresh18
        case lineSearch18
        case lineSend18
        case lineSetting18
        case lineShare18
        case lineShareLink18
        case lineStar18
        case lineStarBadge18
        case lineStop18
        case lineSystemCheck18
        case lineThunder18
        case lineToTop18
        case lineTrash18
        case lineUpload18
        case lineWarning18
        case lineWrite18

        // 24x24
        case fillBag24
        case fillBookmark24
        case fillBoxCheck24
        case fillCamera24
        case fillCheckBadge24
        case fillCircleCheck24
        case fillCommunity24
        case fillFiltering24
        case fillHeart24
        case fillHome24
        case fillLike24
        case fillLock24
        case fillMessege24
        case fillMyPage24
        case fillProfile24
        case fillRadio24
        case fillSearch24
        case fillSend24
        case fillStar24
        case fillStarBadge24
        case fillThunder24
        case fillMyWanted24

        case lineAlramSetting24
        case lineAnswer24
        case lineArrowDown24
        case lineArrowLeft24
        case lineArrowRight24
        case lineArrowUp24
        case lineBag24
        case lineBookmark24
        case lineBoxCheck24
        case lineCalendar24
        case lineCamera24
        case lineCheck24
        case lineCheckBadge24
        case lineCircleAlert24
        case lineCircleCheck24
        case lineCircleHelp24
        case lineCircleInfo24
        case lineCirclePlus24
        case lineCommunity24
        case lineConversation24
        case lineDocument24
        case lineDownload24
        case lineEmail24
        case lineExit24
        case lineExpand24
        case lineFilter24
        case lineFiltering24
        case lineFold24
        case lineFull24
        case lineHandle24
        case lineHeart24
        case lineHome24
        case lineImage24
        case lineLang24
        case lineLangChn24
        case lineLangEng24
        case lineLangJpn24
        case lineLangKor24
        case lineLangMore24
        case lineLike24
        case lineLink24
        case lineLock24
        case lineMappin24
        case lineMenu24
        case lineMenuStar24
        case lineMessege24
        case lineMore24
        case lineMoreVertical24
        case lineMyPage24
        case lineNewtab24
        case lineNotification24
        case linePin24
        case linePlus24
        case lineProfile24
        case lineQuestion24
        case lineRadio24
        case lineRefresh24
        case lineSearch24
        case lineSend24
        case lineSetting24
        case lineShare24
        case lineShareLink24
        case lineStar24
        case lineStarBadge24
        case lineStop24
        case lineSystemCheck24
        case lineThunder24
        case lineToTop24
        case lineTrash24
        case lineUpload24
        case lineWarning24
        case lineWrite24
        case lineMyWanted24

        var name: String { rawValue }
    }
}
