/**
 * Loaders for slim JSON indexes generated by `scripts/build_mcp_data.js`.
 * Files live in `packages/montage-mcp/data/` and are read once at startup.
 */
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export interface InitializerRecord {
  signature: string;
  docId: string;
}

export interface MemberRecord {
  name: string;
  kind: string;
  signature: string;
  summary?: string;
}

export interface NestedTypeRecord {
  name: string;
  kind: string;
  summary?: string;
  cases?: string[];
  modifiers?: MemberRecord[];
  staticMethods?: MemberRecord[];
  staticProperties?: MemberRecord[];
}

export interface ComponentRecord {
  slug: string;
  name: string;
  category: string;
  kind: string;
  declaration: string;
  summary: string;
  initializers: InitializerRecord[];
  modifiers?: MemberRecord[];
  staticMembers?: MemberRecord[];
  nestedTypes: NestedTypeRecord[];
}

export interface ComponentsIndex {
  schema: number;
  generatedAt: string;
  components: ComponentRecord[];
}

export interface TokenSection {
  title: string;
  anchor: string;
  identifiers: string[];
}

export interface TokenRecord {
  name: string;
  kind: string;
  summary: string;
  sections: TokenSection[];
  nestedTypes: NestedTypeRecord[];
}

export interface TokensIndex {
  schema: number;
  generatedAt: string;
  tokens: {
    color: TokenRecord | null;
    typography: TokenRecord | null;
    spacing: TokenRecord | null;
    shadow: TokenRecord | null;
    opacity: TokenRecord | null;
  };
}

export interface IconsIndex {
  schema: number;
  generatedAt: string;
  count: number;
  icons: string[];
}

export interface FigmaMappingIndex {
  version: number;
  description: string;
  components: Record<
    string,
    { montageType: string; swiftSnippet: string; notes?: string }
  >;
  tokens: {
    color: Record<string, string>;
    typography: Record<string, string>;
    spacing: Record<string, string>;
    shadow: Record<string, string>;
    opacity: Record<string, string>;
  };
}

function dataDir(): string {
  // src/core/data/index.ts → ../../../data (when running compiled dist or tsx)
  // dist/server-*.js → ../data (when running bundled output)
  // Fall back: look for "data/components.json" relative to several candidates.
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    resolve(here, "../../../data"),
    resolve(here, "../../data"),
    resolve(here, "../data"),
    resolve(process.cwd(), "data"),
    resolve(process.cwd(), "packages/montage-mcp/data"),
  ];
  for (const c of candidates) {
    try {
      readFileSync(join(c, "components.json"), "utf-8");
      return c;
    } catch {
      // try next
    }
  }
  throw new Error(
    `[montage-ios-mcp] cannot locate slim JSON data dir. Tried: ${candidates.join(", ")}`,
  );
}

let dataDirCached: string | null = null;
function getDataDir(): string {
  if (dataDirCached) return dataDirCached;
  dataDirCached = dataDir();
  return dataDirCached;
}

let componentsCache: ComponentsIndex | null = null;
let tokensCache: TokensIndex | null = null;
let iconsCache: IconsIndex | null = null;
let mappingCache: FigmaMappingIndex | null = null;

function readJson<T>(name: string): T {
  const p = join(getDataDir(), name);
  return JSON.parse(readFileSync(p, "utf-8")) as T;
}

export function loadComponents(): ComponentsIndex {
  if (!componentsCache) componentsCache = readJson<ComponentsIndex>("components.json");
  return componentsCache;
}

export function loadTokens(): TokensIndex {
  if (!tokensCache) tokensCache = readJson<TokensIndex>("tokens.json");
  return tokensCache;
}

export function loadIcons(): IconsIndex {
  if (!iconsCache) iconsCache = readJson<IconsIndex>("icons.json");
  return iconsCache;
}

export function loadFigmaMapping(): FigmaMappingIndex {
  if (!mappingCache) mappingCache = readJson<FigmaMappingIndex>("figma-mapping.json");
  return mappingCache;
}

export function findComponent(name: string): ComponentRecord | undefined {
  const idx = loadComponents();
  const lower = name.toLowerCase();
  return idx.components.find(
    (c) => c.name.toLowerCase() === lower || c.slug === lower,
  );
}

export function listCategories(): Record<string, ComponentRecord[]> {
  const idx = loadComponents();
  const out: Record<string, ComponentRecord[]> = {};
  for (const c of idx.components) {
    (out[c.category] ??= []).push(c);
  }
  return out;
}
