//
//  ElevationPreviewPresenter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/02/16.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

// MARK: - ElevationPreviewPresenter

final class ElevationPreviewPresenter {
    weak var viewController: ElevationPreviewDisplayLogic?
}

// MARK: - ElevationPresentationLogic

extension ElevationPreviewPresenter: ElevationPresentationLogic {
    func present(_ response: ElevationPreview.Response) {
        switch response {
        case .elevationList:
            viewController?.display(
                ElevationPreview.ViewModel.List(
                    items: [
                        .init(name: "Normal", elevation: .shadowNormal),
                        .init(name: "Emphasize", elevation: .shadowEmphasize),
                        .init(name: "Strong", elevation: .shadowStrong),
                        .init(name: "Heavy", elevation: .shadowHeavy)
                    ]
                )
            )
        }
    }
}

// MARK: - ElevationPreviewDisplayLogic definition

protocol ElevationPreviewDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: ElevationPreview.ViewModel.List)
}
