//
//  ElevationPreviewBuilder.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/02/16.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ElevationPreviewBuilder

final class ElevationPreviewBuilder {

}

// MARK: - ElevationBuildingLogic

extension ElevationPreviewBuilder: ElevationBuildingLogic {
    
    func build() -> Destination {
        let viewController = ElevationPreviewController()
        let interactor = ElevationPreviewInteractor()
        let presenter = ElevationPreviewPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - ElevationBuildingLogic definition

protocol ElevationBuildingLogic {
    typealias Destination = ElevationPreviewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build() -> Destination
}
