//
//  ElevationModels.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/02/16.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

enum ElevationPreview {

    enum Request {
        struct OnLoad {}
    }
    
    enum Response: Equatable {
        case elevationList
    }
    
    enum ViewModel {
        struct List {
            let items: [Item]
        }
        
        struct Item: Hashable {
            let id = UUID()
            let name: String
            let elevation: Elevation
            
            func hash(into hasher: inout Hasher) {
                hasher.combine(id)
            }
        }
    }
}
