//
//  ElevationPreviewInteractor.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/02/16.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

// MARK: - ElevationPreviewInteractor

final class ElevationPreviewInteractor {
    var presenter: ElevationPresentationLogic?

    /// 자유롭게 매개변수 추가하기. worker, listener 등등  (Add parameters freely. worker, listener, etc)
    init() {}
}

// MARK: - ElevationPreviewRequestLogic

extension ElevationPreviewInteractor: ElevationPreviewRequestLogic {
    
    func process(_ request: ElevationPreview.Request.OnLoad) {
        presenter?.present(.elevationList)
    }
}

// MARK: - ElevationRequestLogic definition

protocol ElevationPreviewRequestLogic {
    /// 외부매개변수는 제외하기
    func process(_ request: ElevationPreview.Request.OnLoad)
}

// MARK: - ElevationPresentationLogic definition

protocol ElevationPresentationLogic {
    /// 외부매개변수는 제외하기
    func present(_ response: ElevationPreview.Response)
}

