//
//  ElevationPreviewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/02/16.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage
import SnapKit

// MARK: - ElevationPreviewController

final class ElevationPreviewController: BaseViewController {
    typealias Item = ElevationPreview.ViewModel.Item
    typealias DataSource = UICollectionViewDiffableDataSource<String, Item>
    typealias Snapshot = NSDiffableDataSourceSnapshot<String, Item>
    
    private lazy var collectionView: UICollectionView = {
        var config = UICollectionLayoutListConfiguration(appearance: .plain)
        config.showsSeparators = false
        config.backgroundColor = .semantic(.backgroundNormal)
        let layout = UICollectionViewCompositionalLayout.list(using: config)
        return UICollectionView(frame: view.bounds, collectionViewLayout: layout)
    }()
    
    lazy var dataSource: DataSource = makeDataSource()
    
    var interactor: ElevationPreviewRequestLogic?

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        
        interactor?.process(ElevationPreview.Request.OnLoad())
    }
}

extension ElevationPreviewController {
    private func setupViews() {
        title = "Elevation"
        
        setupCollectionView()
    }
    
    private func setupCollectionView() {
        view.addSubview(collectionView)
        setContentScrollView(collectionView)
        
        collectionView.backgroundColor = .semantic(.backgroundNormal)
        collectionView.register(ElevationPreviewCell.self)

        collectionView.snp.makeConstraints {
            $0.top.left.right.equalTo(view.safeAreaLayoutGuide)
            $0.bottom.equalToSuperview()
        }
    }
}

extension ElevationPreviewController {
    private func makeDataSource() -> DataSource {
        let dataSource = DataSource(collectionView: collectionView) { collectionView, indexPath, item in
            let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as ElevationPreviewCell
            cell.configure(with: item)
            return cell
        }
        
        return dataSource
    }
}

// MARK: - ElevationPreviewDisplayLogic

extension ElevationPreviewController: ElevationPreviewDisplayLogic {
    func display(_ viewModel: ElevationPreview.ViewModel.List) {
        var snapshot = dataSource.snapshot()
        snapshot.deleteAllItems()
        snapshot.appendSections(["Elevations"])
        snapshot.appendItems(viewModel.items)
        dataSource.apply(snapshot, animatingDifferences: true)
    }
}
