//
//  BadgePreviewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/04/26.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftUI
import Montage

struct ContentBadgePreview: View {
    @State private var showTransparentChecker: Bool = false
    @State private var isSolid: Bool = true
    @State private var sizeIndex: Int = 0
    @State private var colorStyleIndex: Int = 0
    @State private var leadingIcon: Bool = false
    @State private var trailingIcon: Bool = false
    @State private var foregroundColor: SwiftUI.Color = .semantic(.labelAlternative)
    @State private var backgroundColor: SwiftUI.Color = .semantic(.accentBackgroundViolet)
    
    private let sizes: [ContentBadge.Size] = [
        .xsmall,
        .small,
        .medium
    ]
    
    var body: some View {
        SwiftUI.ScrollView {
            VStack {
                HStack {
                    Text("Preview").bold()
                    Spacer()
                    Button(action: {
                        showTransparentChecker.toggle()
                    }) {
                        Image(systemName: "checkerboard.rectangle")
                            .foregroundColor(.semantic(.primaryNormal))
                    }
                }
                ContentBadge(
                    variant: isSolid ? .solid : .outlined,
                    text: "Badge"
                )
                .size(sizes[sizeIndex])
                .colorStyle(
                    colorStyleIndex == 0 ? .neutral(foregroundColor) : .accent(foregroundColor, background: backgroundColor)
                )
                .modifying { original in
                    if leadingIcon && trailingIcon {
                        original.leadingIcon(.apps).trailingIcon(.apps)
                    } else if leadingIcon {
                        original.leadingIcon(.apps)
                    } else if trailingIcon {
                        original.trailingIcon(.apps)
                    } else {
                        original
                    }
                }
                
            }
            .padding()
            VStack(alignment: .leading) {
                Text("Options").bold()
                HStack {
                    Text("solid")
                    Control.switch(checked: isSolid) { isSolid = $0 }
                }
                HStack {
                    Text("size")
                    SegmentedControl(selectedIndex: $sizeIndex, labels: sizes.map(\.description))
                        .size(.small)
                }
                HStack {
                    Text("colorStyle")
                    SegmentedControl(selectedIndex: $colorStyleIndex, labels: colorStyles.map(\.description))
                        .size(.small)
                }
                SwiftUI.ColorPicker("contentColor", selection: $foregroundColor)
                if colorStyleIndex == 1 {
                    SwiftUI.ColorPicker("backgroundColor", selection: $backgroundColor)
                }
                HStack {
                    Text("leadingIcon")
                    Control.switch(checked: leadingIcon) { leadingIcon = $0 }
                }
                HStack {
                    Text("trailingIcon")
                    Control.switch(checked: trailingIcon) { trailingIcon = $0 }
                }
            }
            .padding(.horizontal)
            .onChange(of: colorStyleIndex) { newValue in
                if newValue == 0 {
                    foregroundColor = .semantic(.labelAlternative)
                }
            }
        }
        .transparentChecking(isPresented: showTransparentChecker, checkerSize: 51, checkerColor: .red)
        .background(SwiftUI.Color.semantic(.backgroundNormal))
    }
    
    private var colorStyles: [ContentBadge.ColorStyle] {
        [
            .neutral(foregroundColor),
            .accent(foregroundColor, background: backgroundColor)
        ]
    }
}

extension ContentBadge.Size: CaseDescribable {}
extension ContentBadge.ColorStyle: CaseDescribable {}

#Preview {
    ContentBadgePreview()
}
