//
//  BadgePreviewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/04/26.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftUI
import Montage

struct ContentBadgePreview: View {
    @State private var isSolid: Bool = true
    @State private var sizeIndex: Int = 0
    @State private var colorStyleIndex: Int = 0
    @State private var leadingIcon: Bool = false
    @State private var leadingIconUsesTemplate: Bool = true
    @State private var trailingIcon: Bool = false
    @State private var trailingIconUsesTemplate: Bool = true
    @State private var foregroundColor: SwiftUI.Color = .semantic(.labelAlternative)
    @State private var backgroundColor: SwiftUI.Color = .semantic(.accentBackgroundViolet)
    
    private let sizes: [ContentBadge.Size] = [
        .xsmall,
        .small,
        .medium
    ]
    
    var body: some View {
        PreviewLayout {
            ContentBadge(
                variant: isSolid ? .solid : .outlined,
                text: "Badge"
            )
            .size(sizes[sizeIndex])
            .colorStyle(
                colorStyleIndex == 0 ? .neutral(foregroundColor) : .accent(foregroundColor, background: backgroundColor)
            )
            .modifying { original in
                var mutated = original
                if leadingIcon {
                    mutated = mutated.leadingIcon(.agentColor, usesTemplate: leadingIconUsesTemplate)
                }
                if trailingIcon {
                    mutated = mutated.trailingIcon(.agentColor, usesTemplate: trailingIconUsesTemplate)
                }
                return mutated
            }
        } options: {
            ToggleOptionRow("solid", isOn: $isSolid)
            SegmentedIndexRow("size", index: $sizeIndex, labels: sizes.map(\.description))
            SegmentedIndexRow("colorStyle", index: $colorStyleIndex, labels: colorStyles.map(\.description))
            ColorPickerOptionRow("contentColor", selection: $foregroundColor)
            if colorStyleIndex == 1 {
                ColorPickerOptionRow("backgroundColor", selection: $backgroundColor)
            }
            HStack {
                ToggleOption("leadingIcon", isOn: $leadingIcon)
                if leadingIcon {
                    ToggleOption("usesTemplate", isOn: $leadingIconUsesTemplate)
                }
            }
            HStack {
                ToggleOption("trailingIcon", isOn: $trailingIcon)
                if trailingIcon {
                    ToggleOption("usesTemplate", isOn: $trailingIconUsesTemplate)
                }
            }
        }
        .onChange(of: colorStyleIndex) { newValue in
            if newValue == 0 {
                foregroundColor = .semantic(.labelAlternative)
            }
        }
    }
    
    private var colorStyles: [ContentBadge.ColorStyle] {
        [
            .neutral(foregroundColor),
            .accent(foregroundColor, background: backgroundColor)
        ]
    }
}

extension ContentBadge.Size: CaseDescribable {}
extension ContentBadge.ColorStyle: CaseDescribable {}

#Preview {
    ContentBadgePreview()
}
