//
//  OpacityPreviewModels.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OpacityPreview {

    enum Request {
        struct OnLoad {}
        
        struct OnTouchPaletteButton {}
        
        struct OnChangedSliderValue {
            let currentValue: Float
        }
    }
    
    enum Response {
        case contents(OpacityPreviewContents)
    }
    
    enum ViewModel {
        struct Contents {
            let displayAlpha: CGFloat
            let displayAlphaName: String
            let displayColor: UIColor
        }
    }
}
