//
//  OpacityPreviewPresenter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - OpacityPreviewPresenter

final class OpacityPreviewPresenter {
    weak var viewController: OpacityPreviewDisplayLogic?
}

// MARK: - OpacityPreviewPresentationLogic

extension OpacityPreviewPresenter: OpacityPreviewPresentationLogic {
    
    func present(_ response: OpacityPreview.Response) {
        switch response {
        case .contents(let contents):
            viewController?.display(
                OpacityPreview.ViewModel.Contents(
                    displayAlpha: contents.currentOpacity,
                    displayAlphaName: ".\(contents.currentOpacityName)",
                    displayColor: contents.selectedColor
                )
            )
        }
    }
}

// MARK: - OpacityPreviewDisplayLogic definition

protocol OpacityPreviewDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: OpacityPreview.ViewModel.Contents)
}
