//
//  OpacityPreviewInteractor.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - OpacityPreviewInteractor

final class OpacityPreviewInteractor {
    var presenter: OpacityPreviewPresentationLogic?
    var router: OpacityPreviewRoutingLogic?
    private var contents: OpacityPreviewContents
    private let worker: OpacityPreviewWorkingLogic

    /// 자유롭게 매개변수 추가하기. worker, listener 등등  (Add parameters freely. worker, listener, etc)
    init(contents: OpacityPreviewContents = .init(), worker: OpacityPreviewWorkingLogic) {
        self.contents = contents
        self.worker = worker
    }
}

// MARK: - OpacityPreviewRequestLogic

extension OpacityPreviewInteractor: OpacityPreviewRequestLogic {
    func process(_ request: OpacityPreview.Request.OnLoad) {
        presenter?.present(.contents(contents))
    }
    
    func process(_ request: OpacityPreview.Request.OnTouchPaletteButton) {
        router?.routeToColorPicker(with: self)
    }
    
    func process(_ request: OpacityPreview.Request.OnChangedSliderValue) {
        contents.currentSliderValue = request.currentValue
        presenter?.present(.contents(contents))
    }
}

extension OpacityPreviewInteractor: ColorPickerListener {
    func didSelectedColor(_ color: UIColor) {
        contents.selectedColor = color
        presenter?.present(.contents(contents))
        router?.routeToCloseColorPicker()
    }
    
    func didCancelSelectColor() {
        router?.routeToCloseColorPicker()
    }
}

// MARK: - OpacityPreviewRequestLogic definition

protocol OpacityPreviewRequestLogic {
    /// 외부매개변수는 제외하기
    func process(_ request: OpacityPreview.Request.OnLoad)
    func process(_ request: OpacityPreview.Request.OnTouchPaletteButton)
    func process(_ request: OpacityPreview.Request.OnChangedSliderValue)
}

// MARK: - OpacityPreviewWorkingLogic definition

protocol OpacityPreviewWorkingLogic {
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func doSomeWork()
}

// MARK: - OpacityPreviewPresentationLogic definition

protocol OpacityPreviewPresentationLogic {
    /// 외부매개변수는 제외하기
    func present(_ response: OpacityPreview.Response)
}

// MARK: - OpacityPreviewRoutingLogic definition

protocol OpacityPreviewRoutingLogic {
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func routeToColorPicker(with listener: ColorPickerListener)
    func routeToCloseColorPicker()
}
