//
//  OpacityPreviewWorker.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - OpacityPreviewWorker

final class OpacityPreviewWorker  {

}

// MARK: - OpacityPreviewWorkingLogic

extension OpacityPreviewWorker: OpacityPreviewWorkingLogic {
    
    func doSomeWork() {
        
    }
}
