//
//  OpacityPreviewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage
import SnapKit

// MARK: - OpacityPreviewController

final class OpacityPreviewController: BaseViewController {
    private enum Const {
        static let blockViewSize: CGSize = .init(width: 256, height: 256)
    }
    
    private lazy var paletteItem = UIBarButtonItem(
        image: .init(systemName: "swatchpalette"),
        primaryAction: .init(handler: { [weak self] _ in
            self?.interactor?.process(OpacityPreview.Request.OnTouchPaletteButton())
        })
    )
    
    private lazy var wrapperView = UIView()
    
    private lazy var slider = UISlider()
    
    private lazy var colorBlockView = UIView()
    
    private lazy var alphaNameLabel = UILabel()
    
    var interactor: OpacityPreviewRequestLogic?
    
    var currentViewModel: OpacityPreview.ViewModel.Contents?

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        
        interactor?.process(OpacityPreview.Request.OnLoad())
    }
    
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        super.traitCollectionDidChange(previousTraitCollection)
        updateBorderLayer()
    }
}

extension OpacityPreviewController {
    private func setupViews() {
        title = "Opacity"
        
        view.addSubview(wrapperView)
        
        wrapperView.snp.makeConstraints {
            $0.edges.equalTo(view.safeAreaLayoutGuide).inset(CGFloat.spacing(.pt16))
        }
        
        setupColorBlockView()
        setupSlider()
        setupAlphaNameLabel()
        setupNavigationItem()
    }
    
    private func setupColorBlockView() {
        colorBlockView.layer.cornerRadius = Const.blockViewSize.width / 2
        
        wrapperView.addSubview(colorBlockView)
        
        colorBlockView.snp.makeConstraints {
            $0.top.equalToSuperview()
            $0.centerX.equalToSuperview()
            $0.size.equalTo(Const.blockViewSize)
        }
    }
    
    private func setupSlider() {
        slider.minimumValueImage = .init(systemName: "circle.fill")
        slider.maximumValueImage = .init(systemName: "circle")
        slider.isContinuous = true
        
        slider.addAction(
            .init(handler: { [self] _ in
                self.interactor?.process(
                    OpacityPreview.Request.OnChangedSliderValue(currentValue: slider.value)
                )
            }),
            for: .valueChanged
        )
        
        wrapperView.addSubview(slider)
        
        slider.snp.makeConstraints {
            $0.top.equalTo(colorBlockView.snp.bottom).offset(CGFloat.spacing(.pt32))
            $0.left.right.equalToSuperview().inset(CGFloat.spacing(.pt16))
        }
    }
    
    private func setupAlphaNameLabel() {
        alphaNameLabel.textAlignment = .center
        
        wrapperView.addSubview(alphaNameLabel)
        
        alphaNameLabel.snp.makeConstraints {
            $0.top.equalTo(slider.snp.bottom).offset(CGFloat.spacing(.pt08))
            $0.centerX.equalToSuperview()
        }
    }
    
    private func setupNavigationItem() {
        navigationItem.rightBarButtonItem = paletteItem
    }
    
    private func updateBorderLayer() {
        guard let currentViewModel = currentViewModel else { return }
        
        colorBlockView.layer.borderWidth = 8.0
        colorBlockView.layer.borderColor = currentViewModel.displayColor.cgColor
    }
}

// MARK: - OpacityPreviewDisplayLogic

extension OpacityPreviewController: OpacityPreviewDisplayLogic {
    func display(_ viewModel: OpacityPreview.ViewModel.Contents) {
        currentViewModel = viewModel
        
        let alpha = CGFloat(viewModel.displayAlpha)
        slider.tintColor = viewModel.displayColor
        colorBlockView.backgroundColor = viewModel.displayColor.withAlphaComponent(alpha)
        alphaNameLabel.attributedText = .montage(
            viewModel.displayAlphaName,
            variant: .title3,
            weight: .medium
        )
        
        updateBorderLayer()
    }
}
