//
//  OpacityPreviewBuilder.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - OpacityPreviewBuilder

final class OpacityPreviewBuilder {

}

// MARK: - OpacityPreviewBuildingLogic

extension OpacityPreviewBuilder: OpacityPreviewBuildingLogic {
    
    func build() -> Destination {
        let viewController = OpacityPreviewController()
        let interactor = OpacityPreviewInteractor(worker: OpacityPreviewWorker())
        let presenter = OpacityPreviewPresenter()
        let router = OpacityPreviewRouter(viewController: viewController)
        viewController.interactor = interactor
        interactor.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - OpacityPreviewBuildingLogic definition

protocol OpacityPreviewBuildingLogic {
    typealias Destination = OpacityPreviewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build() -> Destination
}
