//
//  ColorPickerWorker.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ColorPickerWorker

final class ColorPickerWorker  {

}

// MARK: - ColorPickerWorkingLogic

extension ColorPickerWorker: ColorPickerWorkingLogic {
    
    func doSomeWork() {
        
    }
}
