//
//  ColorPickerModels.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ColorPicker {

    enum Request {
        struct OnLoad {}
        
        struct OnTouchCloseButton {}
        
        struct OnSelectSegment {
            let index: Int
        }
        
        struct OnSelectItemAt {
            let indexPath: IndexPath
        }
    }
    
    enum Response {
        case contents(ColorPreviewContents)
    }
    
    enum ViewModel {
        struct Segments {
            let items: [String]
        }
        
        struct Components {
            let categories: [Category]
        }
        
        struct Category {
            let type: String
            let items: [Item]
        }
        
        struct Item: Hashable {
            let id = UUID()
            let name: String
            let color: UIColor
            
            func hash(into hasher: inout Hasher) {
                hasher.combine(id)
            }
        }
    }
}
