//
//  ColorPickerViewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

// MARK: - ColorPickerViewController

final class ColorPickerViewController: UIViewController {
    typealias Item = ColorPicker.ViewModel.Item
    typealias DataSource = UICollectionViewDiffableDataSource<String, Item>
    typealias Snapshot = NSDiffableDataSourceSnapshot<String, Item>
    
    private lazy var collectionView: UICollectionView = {
        var config = UICollectionLayoutListConfiguration(appearance: .plain)
        config.headerMode = .supplementary
        config.backgroundColor = .semantic(.backgroundNormal)
        let layout = UICollectionViewCompositionalLayout.list(using: config)
        let view = UICollectionView(frame: view.bounds, collectionViewLayout: layout)
        view.delegate = self
        return view
    }()
    
    private lazy var colorTypeSegment = UISegmentedControl()

    lazy var dataSource: DataSource = makeDataSource()
    var interactor: ColorPickerRequestLogic?

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        
        interactor?.process(ColorPicker.Request.OnLoad())
    }
}

extension ColorPickerViewController {
    private func setupViews() {
        view.backgroundColor = .semantic(.backgroundNormal)
        setupCollectionView()
    }
    
    private func setupCollectionView() {
        view.addSubview(collectionView)
        setContentScrollView(collectionView)
        
        collectionView.backgroundColor = .clear
        collectionView.register(ColorPickerCell.self)
        
        collectionView.snp.makeConstraints {
            $0.top.left.right.equalTo(view.safeAreaLayoutGuide)
            $0.bottom.equalToSuperview()
        }
    }
}

extension ColorPickerViewController {
    private func makeDataSource() -> DataSource {
        let dataSource = DataSource(collectionView: collectionView) { collectionView, indexPath, item in
            let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as ColorPickerCell
            cell.configure(from: item)
            return cell
        }
        
        let headerRegistration = UICollectionView.SupplementaryRegistration<UICollectionViewListCell>(
            elementKind: UICollectionView.elementKindSectionHeader
        ) { supplementaryView, elementKind, indexPath in
            let headerItem = dataSource.snapshot().sectionIdentifiers[indexPath.section]
            var configuration = supplementaryView.defaultContentConfiguration()
            configuration.text = headerItem
            supplementaryView.contentConfiguration = configuration
        }
        
        dataSource.supplementaryViewProvider = { (collectionView, elementKind, indexPath) in
            switch elementKind {
            case UICollectionView.elementKindSectionHeader:
                return collectionView.dequeueConfiguredReusableSupplementary(
                    using: headerRegistration, for: indexPath
                )
            default:
                return nil
            }
        }
        
        return dataSource
    }
}

extension ColorPickerViewController: UICollectionViewDelegate {
    func collectionView(
        _ collectionView: UICollectionView,
        didSelectItemAt indexPath: IndexPath
    ) {
        interactor?.process(ColorPicker.Request.OnSelectItemAt(indexPath: indexPath))
    }
}

// MARK: - ColorPickerDisplayLogic

extension ColorPickerViewController: ColorPickerDisplayLogic {
    func display(_ viewModel: ColorPicker.ViewModel.Segments) {
        guard colorTypeSegment.numberOfSegments == 0 else { return }
        
        viewModel.items.enumerated().forEach { index, item in
            colorTypeSegment.insertSegment(
                action: .init(title: item, handler: { [self] _ in
                    self.interactor?.process(ColorPicker.Request.OnSelectSegment(index: index))
                }),
                at: index,
                animated: false
            )
        }
        
        if colorTypeSegment.numberOfSegments > 0 {
            colorTypeSegment.selectedSegmentIndex = 0
        }
        
        navigationItem.titleView = colorTypeSegment
    }
    
    func display(_ viewModel: ColorPicker.ViewModel.Components) {
        var snapshot = dataSource.snapshot()
        
        snapshot.deleteAllItems()
        snapshot.appendSections(viewModel.categories.map({ $0.type }))
        
        viewModel.categories.forEach {
            snapshot.appendItems($0.items, toSection: $0.type)
        }
        
        dataSource.apply(snapshot, animatingDifferences: true)
    }
}
