//
//  ColorPickerBuilder.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ColorPickerBuilder

final class ColorPickerBuilder {

}

// MARK: - ColorPickerBuildingLogic

extension ColorPickerBuilder: ColorPickerBuildingLogic {
    
    func build(with listener: ColorPickerListener?) -> Destination {
        let viewController = ColorPickerViewController()
        let interactor = ColorPickerInteractor(worker: ColorPickerWorker(), listener: listener)
        let presenter = ColorPickerPresenter()
        let router = ColorPickerRouter(viewController: viewController)
        viewController.interactor = interactor
        interactor.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - ColorPickerBuildingLogic definition

protocol ColorPickerBuildingLogic {
    typealias Destination = ColorPickerViewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build(with listener: ColorPickerListener?) -> Destination
}
