//
//  ColorPickerInteractor.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ColorPickerInteractor

final class ColorPickerInteractor {
    typealias Contents = ColorPreviewContents
    
    var presenter: ColorPickerPresentationLogic?
    var router: ColorPickerRoutingLogic?
    private var contents: Contents
    private let worker: ColorPickerWorkingLogic
    private weak var listener: ColorPickerListener?

    /// 자유롭게 매개변수 추가하기. worker, listener 등등  (Add parameters freely. worker, listener, etc)
    init(
        contents: Contents = .init(),
        worker: ColorPickerWorkingLogic,
        listener: ColorPickerListener?
    ) {
        self.contents = contents
        self.worker = worker
        self.listener = listener
    }
}

protocol ColorPickerListener: AnyObject {
    func didSelectedColor(_ color: UIColor)
    func didCancelSelectColor()
}

// MARK: - ColorPickerRequestLogic

extension ColorPickerInteractor: ColorPickerRequestLogic {
    func process(_ request: ColorPicker.Request.OnLoad) {
        presenter?.present(.contents(contents))
    }
    
    func process(_ request: ColorPicker.Request.OnSelectSegment) {
        guard let selectedColorType = Contents.ColorType.allCases[safe: request.index] else { return }
        contents.currentColorType = selectedColorType
        presenter?.present(.contents(contents))
    }
    
    func process(_ request: ColorPicker.Request.OnSelectItemAt) {
        let colorSets = contents.fetchColorSets()
        
        guard let selectedColorSet = colorSets[safe: request.indexPath.section] else { return }
        guard let selectedColor = selectedColorSet.colors[safe: request.indexPath.row] else { return }
        
        listener?.didSelectedColor(selectedColor.color)
    }
}

// MARK: - ColorPickerRequestLogic definition

protocol ColorPickerRequestLogic {
    /// 외부매개변수는 제외하기
    func process(_ request: ColorPicker.Request.OnLoad)
    func process(_ request: ColorPicker.Request.OnSelectSegment)
    func process(_ request: ColorPicker.Request.OnSelectItemAt)
}

// MARK: - ColorPickerWorkingLogic definition

protocol ColorPickerWorkingLogic {}

// MARK: - ColorPickerPresentationLogic definition

protocol ColorPickerPresentationLogic {
    /// 외부매개변수는 제외하기
    func present(_ response: ColorPicker.Response)
}

// MARK: - ColorPickerRoutingLogic definition

protocol ColorPickerRoutingLogic {}

