//
//  ColorPickerPresenter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/03/15.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ColorPickerPresenter

final class ColorPickerPresenter {
    weak var viewController: ColorPickerDisplayLogic?
}

// MARK: - ColorPickerPresentationLogic

extension ColorPickerPresenter: ColorPickerPresentationLogic {
    
    func present(_ response: ColorPicker.Response) {
        switch response {
        case .contents(let contents):
            presentSegments(from: contents)
            presentComponents(from: contents)
        }
    }
    
    private func presentSegments(from contents: ColorPreviewContents) {
        viewController?.display(
            ColorPicker.ViewModel.Segments(items: contents.colorTypeNames)
        )
    }
    
    private func presentComponents(from contents: ColorPreviewContents) {
        viewController?.display(
            ColorPicker.ViewModel.Components(
                categories: contents.fetchColorSets().map { colorSet in
                    .init(
                        type: colorSet.name,
                        items: colorSet.colors.map {
                            .init(name: $0.name, color: $0.color)
                        }
                    )
                }
            )
        )
    }
}

// MARK: - ColorPickerDisplayLogic definition

protocol ColorPickerDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: ColorPicker.ViewModel.Segments)
    func display(_ viewModel: ColorPicker.ViewModel.Components)
}
