//
//  Icon.swift
//  Montage
//
//  Created by Eunyeong Kim on 2021/04/20.
//
import Foundation

/// Montage 번들 내에 포함된 아이콘들의 이름들입니다.
public enum Icon: String, CaseIterable {
    case alignCenter
    case alignJustify
    case alignLeft
    case alignRight
    case android
    case apps
    case arrowDown
    case arrowDownThick
    case arrowLeft
    case arrowLeftThick
    case arrowRight
    case arrowRightThick
    case arrowTurnDownLeft
    case arrowTurnDownRight
    case arrowUp
    case arrowUpThick
    case attachment
    case bell
    case bellFill
    case bellPlus
    case blank
    case blankColor
    case bold
    case book
    case bookFill
    case bookmark
    case bookmarkFill
    case bubble
    case bubbleFill
    case bubblePlus
    case bubblePlusFill
    case bulb
    case businessBag
    case businessBagFill
    case calendar
    case calendarPerson
    case camera
    case cameraFill
    case caretDown
    case caretUp
    case certificate
    case change
    case chat
    case check
    case checkThick
    case chevronDoubleLeft
    case chevronDoubleLeftSmall
    case chevronDoubleLeftThick
    case chevronDoubleLeftThickSmall
    case chevronDoubleRight
    case chevronDoubleRightSmall
    case chevronDoubleRightThick
    case chevronDoubleRightThickSmall
    case chevronDown
    case chevronDownSmall
    case chevronDownThick
    case chevronDownThickSmall
    case chevronLeft
    case chevronLeftSmall
    case chevronLeftThick
    case chevronLeftThickSmall
    case chevronLeftTight
    case chevronLeftTightSmall
    case chevronLeftTightThick
    case chevronLeftTightThickSmall
    case chevronRight
    case chevronRightSmall
    case chevronRightThick
    case chevronRightThickSmall
    case chevronRightTight
    case chevronRightTightSmall
    case chevronRightTightThick
    case chevronRightTightThickSmall
    case chevronUp
    case chevronUpSmall
    case chevronUpThick
    case chevronUpThickSmall
    case circle
    case circleBlock
    case circleCheck
    case circleCheckFill
    case circleClose
    case circleCloseFill
    case circleDot
    case circleExclamation
    case circleExclamationFill
    case circleFill
    case circleInfo
    case circleInfoFill
    case circlePlus
    case circlePlusFill
    case circlePoint
    case circleQuestion
    case circleQuestionFill
    case clock
    case clockFill
    case close
    case closeThick
    case code
    case coffee
    case coffeeFill
    case coins
    case coinsFill
    case column
    case company
    case companyCheck
    case companyCheckFill
    case companyFill
    case companyPlus
    case companyPlusFill
    case compass
    case compassFill
    case component
    case componentFill
    case copy
    case crown
    case crownFill
    case desktop
    case desktopFill
    case diamond
    case diamondFill
    case dislike
    case dislikeFill
    case document
    case documentFill
    case documentPerson
    case documentPersonFill
    case documentSearch
    case documentText
    case documentTextFill
    case dot
    case download
    case exclamation
    case externalLink
    case eye
    case eyeFill
    case eyeSlash
    case eyeSlashFill
    case faceSmile
    case faceSmileFill
    case filter
    case filterFill
    case fire
    case fireFill
    case flag
    case flipBackward
    case folder
    case folderFill
    case folderJob
    case folderJobFill
    case folderStar
    case folderStarFill
    case full
    case globe
    case globeFill
    case graduation
    case graduationFill
    case handle
    case handleDesktop
    case heart
    case heartFill
    case heartInHeart
    case heartInHeartFill
    case history
    case home
    case homeFill
    case hourglass
    case image
    case inbox
    case instance
    case keyboard
    case like
    case likeFill
    case lineHorizontal
    case lineHorizontalThick
    case link
    case list
    case listCategory
    case listOrdered
    case location
    case locationFill
    case lock
    case lockFill
    case lockOpen
    case lockOpenFill
    case login
    case logoApple
    case logoAppleColor
    case logoBrunch
    case logoFacebook
    case logoFacebookColor
    case logoGoogleColor
    case logoGooglePlay
    case logoGooglePlayColor
    case logoInstagram
    case logoInstagramColor
    case logoKakao
    case logoKakaoColor
    case logoLinkedIn
    case logoLinkedInColor
    case logoMicrosoft
    case logoMicrosoftColor
    case logoNaverBlog
    case logoNaverBlogColor
    case logoX
    case logoYoutube
    case logoYoutubeColor
    case logout
    case magicWand
    case mail
    case mailOpen
    case medal
    case megaphone
    case megaphoneFill
    case menu
    case menuThick
    case message
    case messageFill
    case microphone
    case microphoneFill
    case microphoneSlash
    case microphoneSlashFill
    case minus
    case minusThick
    case mobile
    case mobileFill
    case moon
    case moreHorizontal
    case moreVertical
    case moreVerticalTight
    case musicMicrophone
    case navigationCareer
    case navigationMenu
    case navigationMypage
    case navigationRecruit
    case navigationSocial
    case palette
    case paletteFill
    case pause
    case pencil
    case pencilFill
    case person
    case personFill
    case personPlus
    case personPlusFill
    case persons
    case personsFill
    case phone
    case phoneFill
    case pin
    case pinFill
    case play
    case plus
    case plusThick
    case presentation
    case printer
    case question
    case quote
    case refresh
    case reset
    case search
    case searchThick
    case send
    case sendFill
    case setting
    case share
    case shareIos
    case sparkle
    case sparkleFill
    case square
    case squareCaret
    case squareCheck
    case squareFill
    case squareHan
    case squareHangul
    case squareKana
    case squareLatin
    case squareLatinFill
    case squareMore
    case squarePlay
    case squarePlus
    case squarePlusFill
    case star
    case starFill
    case strikethrough
    case sun
    case tag
    case tagFill
    case template
    case templateFill
    case textFormat
    case textVariable
    case thumbnail
    case thunder
    case thunderFill
    case ticket
    case ticketFill
    case trash
    case triangle
    case triangleExclamation
    case triangleExclamationFill
    case triangleFill
    case trophy
    case trophyFill
    case tune
    case umbrella
    case umbrellaFill
    case underline
    case upload
    case utility
    case utilityFill
    case verifiedCheck
    case verifiedCheckFill
    case verifiedStar
    case verifiedStarFill
    case video
    case webinar
    case write
    case zepFast
    case zepFastFill

    public var name: String { rawValue }
}
