//
//  SwitchPreview.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/02/27.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage
import SnapKit

// MARK: - SwitchPreview

import SwiftUI
struct SwitchPreview: View {
    @State private var isOn: Bool = false
    @State private var sizeIndex: Int = 0
    @State private var disabled: Bool = false
    
    private let sizes: [Control.Switch.Size] = [
        .small, .medium
    ]
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading) {
                Text("Preview").bold()
                Control.Switch($isOn, size: sizes[sizeIndex]) {
                    print($0)
                }
                .disabled(disabled)
                Text("Options").bold()
                HStack {
                    Text("size")
                    SegmentedControl(selectedIndex: $sizeIndex, labels: sizes.map(\.description))
                        .size(.small)
                }
                HStack {
                    Text("disabled")
                    Control.Switch($disabled)
                }
            }
            .padding()
        }
        .background(SwiftUI.Color.semantic(.backgroundNormal))
    }
}

extension Control.Switch.Size: CaseDescribable {}

#Preview {
    SwitchPreview()
}

