//
//  TypographyPreviewModels.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/17.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

enum TypographyPreview {
    typealias Contents = TypographyPreviewContents

    enum Request {
        struct OnLoad {}
        
        struct OnTouchSizeButton {}
        
        struct OnTouchWeightButton {}
        
        struct OnSelectSizeMenu {
            let index: Int
        }
        
        struct OnSelectWeightMenu {
            let index: Int
        }
        
        struct OnSelectOptionMenu {
            let index: Int
        }
    }
    
    enum Response {
        case contents(Contents)
    }
    
    enum ViewModel {
        struct Category {
            let type: String
            let items: [Item]
        }
        
        struct Item: Hashable {
            let id = UUID()
            let title: String
            let engString: NSAttributedString
            let korString: NSAttributedString
            let jpnString: NSAttributedString
            let showMultiline: Bool
            let showBounds: Bool
            
            func hash(into hasher: inout Hasher) {
                hasher.combine(id)
            }
        }
        
        struct SelectorItem {
            let iconName: String?
            let title: String
            let isSelected: Bool
        }
        
        struct WeightSelector {
            let items: [SelectorItem]
        }
        
        struct OptionSelector {
            let items: [SelectorItem]
        }
    }
}
