//
//  TypographyPresenter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/17.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - TypographyPresenter

final class TypographyPreviewPresenter {
    typealias Contents = TypographyPreviewContents
    
    private enum Const {
        static let engText = "The quick brown fox jumps over a lazy dog. Pack my box with five dozen liquor jugs."
        static let korText = "추운 겨울에는 따뜻한 커피와 티를 마셔야지요. 콩고물과 우유가 들어간 빙수는 차게 먹어야 특별한 맛이 잘 표현된다."
        static let jpnText = "いろはにほへどちりぬるをわがよたれぞつねならむうゐのおくやまけふこえてあさきゆめみじゑひもせず"
    }
    
    weak var viewController: TypographyDisplayLogic?
}

// MARK: - TypographyPresentationLogic

extension TypographyPreviewPresenter: TypographyPresentationLogic {
    func present(_ response: TypographyPreview.Response) {
        switch response {
        case .contents(let contents):
            presentContents(contents)
        }
    }
}

extension TypographyPreviewPresenter {
    private func presentContents(_ contents: Contents) {
        presentCategory(from: contents)
        presentWeightSelector(from: contents)
        presentOptionSelector(from: contents)
    }
    
    private func presentCategory(from contents: Contents) {
        viewController?.display(
            TypographyPreview.ViewModel.Category(
                type: "",
                items: contents.combinations.map {
                    makeSampleText($0, contents.showMultiline, contents.showBounds)
                }
            )
        )
    }
    
    private func presentWeightSelector(from contents: Contents) {
        viewController?.display(
            TypographyPreview.ViewModel.WeightSelector(items: [
                .init(iconName: nil, title: "Regular", isSelected: contents.currentWeight == .regular),
                .init(iconName: nil, title: "Medium", isSelected: contents.currentWeight == .medium),
                .init(iconName: nil, title: "Large", isSelected: contents.currentWeight == .bold)
            ])
        )
    }
    
    private func presentOptionSelector(from contents: Contents) {
        viewController?.display(
            TypographyPreview.ViewModel.OptionSelector(items: [
                .init(iconName: "text.alignleft", title: "여러줄 보기", isSelected: contents.showMultiline),
                .init(iconName: "rectangle.dashed", title: "요소 외곽선 보기", isSelected: contents.showBounds)
            ])
        )
    }
}

extension TypographyPreviewPresenter {
    private func makeSampleText(
        _ combination: Contents.Combination,
        _ showMultiline: Bool,
        _ showBounds: Bool
    ) -> TypographyPreview.ViewModel.Item {
        .init(
            title: String(String(reflecting: combination.variant).split(separator: ".").last ?? "").capitalized,
            engString: makeMontageText(Const.engText, combination),
            korString: makeMontageText(Const.korText, combination),
            jpnString: makeMontageText(Const.jpnText, combination),
            showMultiline: showMultiline,
            showBounds: showBounds
        )
    }
    
    private func makeMontageText(
        _ text: String,
        _ combination: Contents.Combination
    ) -> NSAttributedString {
        .montage(
            text,
            variant: combination.variant,
            weight: combination.weight
        )
    }
}

// MARK: - TypographyDisplayLogic definition

protocol TypographyDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: TypographyPreview.ViewModel.Category)
    func display(_ viewModel: TypographyPreview.ViewModel.WeightSelector)
    func display(_ viewModel: TypographyPreview.ViewModel.OptionSelector)
}
