//
//  TypographyPreviewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/17.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - TypographyPreviewController

final class TypographyPreviewController: BaseViewController {
    typealias Item = TypographyPreview.ViewModel.Item
    typealias DataSource = UICollectionViewDiffableDataSource<String, Item>
    typealias Snapshot = NSDiffableDataSourceSnapshot<String, Item>
    
    private lazy var collectionView: UICollectionView = {
        var config = UICollectionLayoutListConfiguration(appearance: .plain)
        config.itemSeparatorHandler = { (indexPath, sectionSeperatorConfig) in
            var configuration = sectionSeperatorConfig
            configuration.topSeparatorVisibility = .hidden
            configuration.bottomSeparatorInsets = .init(top: 0, leading: 16, bottom: 0, trailing: 0)
            return configuration
        }
        config.backgroundColor = .semantic(.backgroundNormal)
        let layout = UICollectionViewCompositionalLayout.list(using: config)
        return UICollectionView(frame: view.bounds, collectionViewLayout: layout)
    }()
    
    private lazy var weightItem = UIButton(configuration: .plain())
    
    private lazy var optionItem = UIButton(configuration: .plain())

    lazy var dataSource: DataSource = makeDataSource()
    
    var interactor: TypographyRequestLogic?

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        
        interactor?.process(TypographyPreview.Request.OnLoad())
    }
}

extension TypographyPreviewController {
    private func setupViews() {
        title = "Typography"
        
        setupNavigationItem()
        setupCollectionView()
    }
    
    private func setupNavigationItem() {
        let itemStackView = UIStackView()
        itemStackView.axis = .horizontal
        
        itemStackView.addArrangedSubview(weightItem)
        itemStackView.addArrangedSubview(optionItem)
        
        navigationItem.rightBarButtonItem = .init(customView: itemStackView)
    }
    
    private func setupCollectionView() {
        view.addSubview(collectionView)
        setContentScrollView(collectionView)
        
        collectionView.backgroundColor = .clear
        collectionView.register(TypographyItemCell.self)
        
        collectionView.snp.makeConstraints {
            $0.top.left.right.equalTo(view.safeAreaLayoutGuide)
            $0.bottom.equalToSuperview()
        }
    }
}

extension TypographyPreviewController {
    private func makeDataSource() -> DataSource {
        let dataSource = DataSource(collectionView: collectionView) { collectionView, indexPath, item in
            let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as TypographyItemCell
            cell.configure(with: item)
            return cell
        }
        
        return dataSource
    }
}

// MARK: - TypographyDisplayLogic

extension TypographyPreviewController: TypographyDisplayLogic {
    func display(_ viewModel: TypographyPreview.ViewModel.Category) {
        var snapshot = dataSource.snapshot()
        snapshot.deleteAllItems()
        snapshot.appendSections([""])
        snapshot.appendItems(viewModel.items)
        dataSource.apply(snapshot, animatingDifferences: true)
    }
    
    func display(_ viewModel: TypographyPreview.ViewModel.WeightSelector) {
        let actions = viewModel.items.enumerated().map { index, item in
            UIAction(
                title: item.title,
                state: item.isSelected ? .on : .off
            ) { [self] _ in
                self.interactor?.process(TypographyPreview.Request.OnSelectWeightMenu(index: index))
            }
        }
        
        weightItem.menu = UIMenu(children: actions)
        weightItem.setImage(.init(systemName: "lineweight"), for: .normal)
        weightItem.showsMenuAsPrimaryAction = true
    }
    
    func display(_ viewModel: TypographyPreview.ViewModel.OptionSelector) {
        let actions = viewModel.items.enumerated().map { index, item in
            UIAction(
                title: item.title,
                image: .init(systemName: item.iconName ?? ""),
                state: item.isSelected ? .on : .off
            ) { [self] _ in
                self.interactor?.process(TypographyPreview.Request.OnSelectOptionMenu(index: index))
            }
        }
        
        optionItem.menu = UIMenu(children: actions)
        optionItem.setImage(.init(systemName: "gear"), for: .normal)
        optionItem.showsMenuAsPrimaryAction = true
    }
}
