//
//  TypographyPreviewBuilder.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/17.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - TypographyPreviewBuilder

final class TypographyPreviewBuilder {

}

// MARK: - TypographyPreviewBuildingLogic

extension TypographyPreviewBuilder: TypographyPreviewBuildingLogic {
    
    func build() -> Destination {
        let viewController = TypographyPreviewController()
        let interactor = TypographyPreviewInteractor()
        let presenter = TypographyPreviewPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - TypographyBuildingLogic definition

protocol TypographyPreviewBuildingLogic {
    typealias Destination = TypographyPreviewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build() -> Destination
}
