//
//  TypographyPreviewInteractor.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/17.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Montage

// MARK: - TypographyPreviewInteractor

final class TypographyPreviewInteractor {
    var presenter: TypographyPresentationLogic?
    private var contents: TypographyPreviewContents

    /// 자유롭게 매개변수 추가하기. worker, listener 등등  (Add parameters freely. worker, listener, etc)
    init(contents: TypographyPreviewContents = .init()) {
        self.contents = contents
    }
}

// MARK: - TypographyRequestLogic

extension TypographyPreviewInteractor: TypographyRequestLogic {
    func process(_ request: TypographyPreview.Request.OnLoad) {
        presenter?.present(.contents(contents))
    }
    
    func process(_ request: TypographyPreview.Request.OnSelectWeightMenu) {
        guard let selectedWeight = Typography.Weight.allCases[safe: request.index] else { return }
        
        contents.currentWeight = selectedWeight
        presenter?.present(.contents(contents))
    }
    
    func process(_ request: TypographyPreview.Request.OnSelectOptionMenu) {
        switch request.index {
        case 0:
            contents.showMultiline.toggle()
        case 1:
            contents.showBounds.toggle()
        default:
            break
        }
        
        presenter?.present(.contents(contents))
    }
}

// MARK: - TypographyRequestLogic definition

protocol TypographyRequestLogic {
    /// 외부매개변수는 제외하기
    func process(_ request: TypographyPreview.Request.OnLoad)
    func process(_ request: TypographyPreview.Request.OnSelectWeightMenu)
    func process(_ request: TypographyPreview.Request.OnSelectOptionMenu)
}

// MARK: - TypographyWorkingLogic definition

protocol TypographyWorkingLogic {
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func doSomeWork()
}

// MARK: - TypographyPresentationLogic definition

protocol TypographyPresentationLogic {
    /// 외부매개변수는 제외하기
    func present(_ response: TypographyPreview.Response)
}

// MARK: - TypographyRoutingLogic definition

protocol TypographyRoutingLogic {
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func routeToSomewhere()
}

