//
//  ColorPreviewPresenter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/18.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ColorPreviewPresenter

final class ColorPreviewPresenter {
    weak var viewController: ColorPreviewDisplayLogic?
}

// MARK: - ColorPreviewPresentationLogic

extension ColorPreviewPresenter: ColorPreviewPresentationLogic {
    
    func present(_ response: ColorPreview.Response) {
        switch response {
        case .colorSets(let colorSets):
            viewController?.display(
                ColorPreview.ViewModel.List(
                    categories: colorSets.map { category in
                        ColorPreview.ViewModel.Category(
                            type: category.name,
                            items: category.colors.map { item in
                                .init(name: item.name,color: item.color, axis: item.axis)
                            },
                            axis: category.axis
                        )
                    }
                )
            )
        case .paletteSelector:
            viewController?.display(
                ColorPreview.ViewModel.PaletteSelector(items: ["Atomic", "Semantic"])
            )
        case .transparentChecker(let isOn):
            viewController?.display(ColorPreview.ViewModel.TransparentChecker(isOn: isOn))
        }
    }
}

// MARK: - ColorDisplayLogic definition

protocol ColorPreviewDisplayLogic: AnyObject {
    func display(_ viewModel: ColorPreview.ViewModel.List)
    func display(_ viewModel: ColorPreview.ViewModel.PaletteSelector)
    func display(_ viewModel: ColorPreview.ViewModel.TransparentChecker)
}
