//
//  ColorModels.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/18.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

enum ColorPreview {
    enum Request {
        struct OnLoad {}
        
        struct OnTouchPaletteButton {}
        
        struct OnTouchTransparentCheckButton {}
        
        struct OnSelectPalette {
            let index: Int
        }
    }
    
    enum Response: Equatable {
        case colorSets([ColorPreviewSet])
        case paletteSelector
        case transparentChecker(Bool)
    }
    
    enum ViewModel {
        struct List {
            let categories: [Category]
        }
        
        struct Category {
            let type: String
            let items: [Item]
            let axis: NSLayoutConstraint.Axis
        }
        
        struct Item: Hashable {
            let id = UUID()
            let name: String
            let color: UIColor
            let axis: NSLayoutConstraint.Axis
            
            func hash(into hasher: inout Hasher) {
                hasher.combine(id)
            }
        }
        
        struct PaletteSelector {
            let items: [String]
        }
        
        struct TransparentChecker {
            let isOn: Bool
        }
    }
    
    struct ColorPreviewSet: Equatable {
        let name: String
        let colors: [ColorPreviewChip]
        let axis: NSLayoutConstraint.Axis
    }
    
    struct ColorPreviewChip: Equatable {
        let name: String
        let color: UIColor
        let axis: NSLayoutConstraint.Axis
    }
}
