//
//  ColorPreviewInteractor.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/18.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Montage

// MARK: - ColorPreviewInteractor

final class ColorPreviewInteractor {
    var presenter: ColorPreviewPresentationLogic?
    private let contents: ColorPreviewContents

    /// 자유롭게 매개변수 추가하기. worker, listener 등등  (Add parameters freely. worker, listener, etc)
    init(contents: ColorPreviewContents) {
        self.contents = contents
    }
}

// MARK: - ColorPreviewRequestLogic

extension ColorPreviewInteractor: ColorPreviewRequestLogic {
    func process(_ request: ColorPreview.Request.OnLoad) {
        presenter?.present(.colorSets(contents.fetchColorSets()))
    }
    
    func process(_ request: ColorPreview.Request.OnTouchPaletteButton) {
        presenter?.present(.paletteSelector)
    }
    
    func process(_ request: ColorPreview.Request.OnTouchTransparentCheckButton) {
        contents.usingTransparentCheck = !contents.usingTransparentCheck
        presenter?.present(.transparentChecker(contents.usingTransparentCheck))
    }
    
    func process(_ request: ColorPreview.Request.OnSelectPalette) {
        switch request.index {
        case 0:
            contents.currentColorType = .atomic
        case 1:
            contents.currentColorType = .sementic
        default:
            break
        }
        
        presenter?.present(.colorSets(contents.fetchColorSets()))
    }
}

// MARK: - ColorPreviewRequestLogic definition

protocol ColorPreviewRequestLogic {
    /// 외부매개변수는 제외하기
    func process(_ request: ColorPreview.Request.OnLoad)
    func process(_ request: ColorPreview.Request.OnTouchPaletteButton)
    func process(_ request: ColorPreview.Request.OnTouchTransparentCheckButton)
    func process(_ request: ColorPreview.Request.OnSelectPalette)
}

// MARK: - ColorPresentationLogic definition

protocol ColorPreviewPresentationLogic {
    /// 외부매개변수는 제외하기
    func present(_ response: ColorPreview.Response)
}

