//
//  ColorPreviewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/18.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

// MARK: - ColorPreviewController

final class ColorPreviewController: BaseViewController {
    typealias Item = ColorPreview.ViewModel.Item
    typealias DataSource = UICollectionViewDiffableDataSource<String, Item>
    typealias Snapshot = NSDiffableDataSourceSnapshot<String, Item>
    
    private lazy var collectionView = UICollectionView(
        frame: view.bounds,
        collectionViewLayout: makeCustomLayout()
    )
    
    private lazy var transparentCheckItem = UIBarButtonItem(
        image: .init(systemName: "cube.transparent"),
        primaryAction: .init(handler: { [weak self] _ in
            self?.interactor?.process(ColorPreview.Request.OnTouchTransparentCheckButton())
        })
    )
    
    private lazy var paletteItem = UIBarButtonItem(
        image: .init(systemName: "swatchpalette"),
        primaryAction: .init(handler: { [weak self] _ in
            self?.interactor?.process(ColorPreview.Request.OnTouchPaletteButton())
        })
    )
    
    lazy var dataSource: DataSource = makeDataSource()
    var interactor: ColorPreviewRequestLogic?
    
    private var currentViewModel: ColorPreview.ViewModel.List?
    private var usingTransparentChecker: Bool = false

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        
        interactor?.process(ColorPreview.Request.OnLoad())
    }
}

extension ColorPreviewController {
    private func setupViews() {
        title = "Color"
        
        setupCollectionView()
        setupNavigationItem()
    }
    
    private func setupNavigationItem() {
        navigationItem.rightBarButtonItems = [transparentCheckItem, paletteItem]
    }
    
    private func setupCollectionView() {
        view.addSubview(collectionView)
        setContentScrollView(collectionView)
        
        collectionView.backgroundColor = .clear
        collectionView.register(ColorChipCell.self)
        collectionView.register(SectionHeaderCell.self)
        
        collectionView.snp.makeConstraints {
            $0.top.left.right.equalTo(view.safeAreaLayoutGuide)
            $0.bottom.equalToSuperview()
        }
    }
}

extension ColorPreviewController {
    private func makeCustomLayout() -> UICollectionViewCompositionalLayout {
        let configuration = UICollectionViewCompositionalLayoutConfiguration()
        configuration.interSectionSpacing = 20
        
        return UICollectionViewCompositionalLayout(
            sectionProvider: makeCustomLayoutSection,
            configuration: configuration
        )
    }
    
    private func makeCustomLayoutSection(
        _ sectionIndex: Int,
        _ layoutEnvironment: NSCollectionLayoutEnvironment
    ) -> NSCollectionLayoutSection {
        guard let sectionViewModel = currentViewModel?.categories[safe: sectionIndex] else {
            return .list(using: .init(appearance: .plain), layoutEnvironment: layoutEnvironment)
        }
        
        let axis = sectionViewModel.axis
        let itemSize = NSCollectionLayoutSize(
            widthDimension: axis == .horizontal ? .absolute(60) : .fractionalWidth(1.0),
            heightDimension: axis == .horizontal ? .absolute(80) : .absolute(60)
        )
        
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        
        let group: NSCollectionLayoutGroup
        
        switch axis {
        case .horizontal:
            group = NSCollectionLayoutGroup.vertical(layoutSize: itemSize, subitems: [item])
        case .vertical:
            group = NSCollectionLayoutGroup.horizontal(layoutSize: itemSize, subitems: [item])
        @unknown default:
            fatalError()
        }
        
        group.interItemSpacing = .fixed(0)
        
        let headerItem = NSCollectionLayoutBoundarySupplementaryItem(
            layoutSize: .init(widthDimension: .fractionalWidth(1.0), heightDimension: .absolute(40)),
            elementKind: UICollectionView.elementKindSectionHeader,
            alignment: .topLeading
        )
        headerItem.extendsBoundary = true
        
        let section = NSCollectionLayoutSection(group: group)
        section.boundarySupplementaryItems = [headerItem]
        section.orthogonalScrollingBehavior = axis == .horizontal ? .continuousGroupLeadingBoundary : .none
        section.contentInsets = .init(top: 0, leading: 20, bottom: 0, trailing: 20)
        
        return section
    }
    
    private func makeDataSource() -> DataSource {
        let dataSource = DataSource(collectionView: collectionView) { collectionView, indexPath, item in
            let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as ColorChipCell
            cell.configure(with: item, usingTransparentChecker: self.usingTransparentChecker)
            return cell
        }
        
        let headerRegistration = UICollectionView.SupplementaryRegistration<SectionHeaderCell>(
            elementKind: UICollectionView.elementKindSectionHeader
        ) { supplementaryView, elementKind, indexPath in
            let headerItem = dataSource.snapshot().sectionIdentifiers[indexPath.section]
            supplementaryView.title = headerItem
        }
        
        dataSource.supplementaryViewProvider = { (collectionView, elementKind, indexPath) in
            switch elementKind {
            case UICollectionView.elementKindSectionHeader:
                return collectionView.dequeueConfiguredReusableSupplementary(
                    using: headerRegistration, for: indexPath
                )
            default:
                return nil
            }
        }
        
        return dataSource
    }
}

// MARK: - ColorPreviewDisplayLogic

extension ColorPreviewController: ColorPreviewDisplayLogic {
    func display(_ viewModel: ColorPreview.ViewModel.List) {
        currentViewModel = viewModel
        
        var snapshot = dataSource.snapshot()
        snapshot.deleteAllItems()
        snapshot.appendSections(viewModel.categories.map { $0.type })
        
        viewModel.categories.forEach {
            snapshot.appendItems($0.items, toSection: $0.type)
        }
        
        dataSource.apply(snapshot, animatingDifferences: true)
    }
    
    func display(_ viewModel: ColorPreview.ViewModel.PaletteSelector) {
        let bottomSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        
        viewModel.items.enumerated().forEach { (index, item) in
            bottomSheet.addAction(.init(title: item, style: .default, handler: { [weak self] _ in
                self?.interactor?.process(ColorPreview.Request.OnSelectPalette(index: index))
            }))
        }
        
        bottomSheet.popoverPresentationController?.barButtonItem = paletteItem
        
        bottomSheet.addAction(.init(title: "취소", style: .cancel))
        
        present(bottomSheet, animated: true)
    }
    
    func display(_ viewModel: ColorPreview.ViewModel.TransparentChecker) {
        transparentCheckItem.image = UIImage(
            systemName: viewModel.isOn ? "cube.transparent.fill" : "cube.transparent"
        )
        usingTransparentChecker = viewModel.isOn
        
        collectionView.reloadData()
    }
}
