//
//  ColorPreviewBuilder.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/18.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ColorPreviewBuilder

final class ColorPreviewBuilder {

}

// MARK: - ColorPreviewBuildingLogic

extension ColorPreviewBuilder: ColorPreviewBuildingLogic {
    
    func build() -> Destination {
        let viewController = ColorPreviewController()
        let interactor = ColorPreviewInteractor(contents: ColorPreviewContents())
        let presenter = ColorPreviewPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - ColorBuildingLogic definition

protocol ColorPreviewBuildingLogic {
    typealias Destination = ColorPreviewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build() -> Destination
}
