//
//  ComponentListBuilder.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ComponentListBuilder

final class ComponentListBuilder {

}

// MARK: - ComponentListBuildingLogic

extension ComponentListBuilder: ComponentListBuildingLogic {
    
    func build() -> Destination {
        let viewController = ComponentListViewController()
        let interactor = ComponentListInteractor(worker: ComponentListWorker())
        let presenter = ComponentListPresenter()
        let router = ComponentListRouter(viewController: viewController)
        viewController.interactor = interactor
        interactor.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - ComponentListBuildingLogic definition

protocol ComponentListBuildingLogic {
    typealias Destination = ComponentListViewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build() -> Destination
}
