//
//  ComponentListInteractor.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

// MARK: - ComponentListInteractor

final class ComponentListInteractor {
    var presenter: ComponentListPresentationLogic?
    var router: ComponentListRoutingLogic?
    private let worker: ComponentListWorkingLogic
    private var contents: ComponentListContents
    
    init(contents: ComponentListContents = .init(), worker: ComponentListWorkingLogic) {
        self.contents = contents
        self.worker = worker
    }
}

// MARK: - ComponentListRequestLogic

extension ComponentListInteractor: ComponentListRequestLogic {
    func onLoad() {
        presenter?.presentItems(contents.usableCategoryItems)
    }
    
    func onSelectItem(at indexPath: IndexPath) {
        guard let itemSet = contents.usableCategoryItems[safe: indexPath.section] else { return }
        guard let item = itemSet.items[safe: indexPath.row] else { return }
        
        router?.routeToComponent(item)
    }
    
    func onSearch(_ term: String) {
        contents.searchTerm = term
        presenter?.presentItems(contents.usableCategoryItems)
    }
}

// MARK: - ComponentListRequestLogic definition

protocol ComponentListRequestLogic {
    func onLoad()
    func onSelectItem(at indexPath: IndexPath)
    func onSearch(_ term: String)
}

// MARK: - ComponentListWorkingLogic definition

protocol ComponentListWorkingLogic {}

// MARK: - ComponentListPresentationLogic definition

protocol ComponentListPresentationLogic {
    func presentItems(_ items: [ComponentListContents.CategoryItemSet])
}

// MARK: - ComponentListRoutingLogic definition

protocol ComponentListRoutingLogic {
    func routeToComponent(_ itemType: ComponentListContents.ComponentType)
}

