//
//  ComponentsViewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit
import Montage

// MARK: - ComponentsViewController

final class ComponentListViewController: BaseViewController {
    typealias Item = ComponentList.ViewModel.Item
    typealias DataSource = UICollectionViewDiffableDataSource<String, Item>
    typealias Snapshot = NSDiffableDataSourceSnapshot<String, Item>
    
    private lazy var stackView: UIStackView = {
        let view = UIStackView()
        view.axis = .vertical
        view.spacing = 0
        return view
    }()
    
    private lazy var searchBar: UISearchBar = {
        let searchBar = UISearchBar()
        searchBar.delegate = self
        return searchBar
    }()
    
    private lazy var collectionView: UICollectionView = {
        var config = UICollectionLayoutListConfiguration(appearance: .plain)
        config.headerMode = .supplementary
        config.backgroundColor = .semantic(.backgroundNormal)
        let layout = UICollectionViewCompositionalLayout.list(using: config)
        let view = UICollectionView(frame: view.bounds, collectionViewLayout: layout)
        view.delegate = self
        return view
    }()

    lazy var dataSource: DataSource = makeDataSource()
    var interactor: ComponentListRequestLogic?

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        
        interactor?.onLoad()
    }
}

extension ComponentListViewController {
    private func setupViews() {
        title = "Montage"
        
        view.addSubview(stackView)
        stackView.addArrangedSubview(searchBar)
        searchBar.becomeFirstResponder()
        
        stackView.addArrangedSubview(collectionView)
        
        setContentScrollView(collectionView)
        
        collectionView.backgroundColor = .clear
        collectionView.register(ComponentItemCell.self)
        
        stackView.snp.makeConstraints {
            $0.top.left.right.equalTo(view.safeAreaLayoutGuide)
            $0.bottom.equalToSuperview()
        }
    }
}

extension ComponentListViewController {
    private func makeDataSource() -> DataSource {
        let dataSource = DataSource(collectionView: collectionView) { collectionView, indexPath, item in
            let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as ComponentItemCell
            cell.configure(from: item)
            return cell
        }
        
        let headerRegistration = UICollectionView.SupplementaryRegistration<UICollectionViewListCell>(
            elementKind: UICollectionView.elementKindSectionHeader
        ) { supplementaryView, elementKind, indexPath in
            let headerItem = dataSource.snapshot().sectionIdentifiers[indexPath.section]
            var configuration = supplementaryView.defaultContentConfiguration()
            configuration.text = headerItem
            supplementaryView.contentConfiguration = configuration
        }
        
        dataSource.supplementaryViewProvider = { (collectionView, elementKind, indexPath) in
            switch elementKind {
            case UICollectionView.elementKindSectionHeader:
                return collectionView.dequeueConfiguredReusableSupplementary(
                    using: headerRegistration, for: indexPath
                )
            default:
                return nil
            }
        }
        
        return dataSource
    }
}

extension ComponentListViewController: UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        interactor?.onSearch(searchText)
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        searchBar.resignFirstResponder()
    }
}

extension ComponentListViewController: UICollectionViewDelegate {
    func collectionView(
        _ collectionView: UICollectionView,
        didSelectItemAt indexPath: IndexPath
    ) {
        interactor?.onSelectItem(at: indexPath)
    }
}

// MARK: - ComponentListDisplayLogic

extension ComponentListViewController: ComponentListDisplayLogic {
    func display(_ viewModel: ComponentList.ViewModel.Components) {
        var snapshot = dataSource.snapshot()
        
        snapshot.appendSections(
            viewModel.categories.map { $0.type }
                .filter { !snapshot.sectionIdentifiers.contains($0) }
        )
        
        snapshot.sectionIdentifiers.forEach { section in
            snapshot.deleteItems(snapshot.itemIdentifiers(inSection: section))
            if let category = viewModel.categories.first(where: { $0.type == section }) {
                snapshot.appendItems(
                    category.items,
                    toSection: section
                )
            }
        }
        
        dataSource.apply(snapshot, animatingDifferences: true)
    }
}
