//
//  ComponentListWorker.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ComponentListWorker

final class ComponentListWorker {}

// MARK: - ComponentListWorkingLogic

extension ComponentListWorker: ComponentListWorkingLogic {}
