//
//  ComponentListRouter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftUI
import Montage

// MARK: - ComponentListRouter

final class ComponentListRouter: NSObject {
    weak var viewController: UIViewController?
    
    /// 자유롭게 다른 scene builder 추가하기 (Freely add builders of different scenes)
    init(viewController: UIViewController) {
        self.viewController = viewController
    }
}

// MARK: - ComponentListRoutingLogic

extension ComponentListRouter: ComponentListRoutingLogic {
    func routeToComponent(_ itemType: ComponentListContents.ComponentType) {
        let vc: UIViewController
        
        switch itemType {
        case .typography:
            vc = TypographyPreviewBuilder().build()
        case .color:
            vc = ColorPreviewBuilder().build()
        case .icon, .grid:
            vc = IconPreviewBuilder().build()
        case .elevation:
            vc = ElevationPreviewBuilder().build()
        case .switch:
            vc = UIHostingController(rootView: SwitchPreview())
        case .input:
            vc = UIHostingController(rootView: InputPreview())
        case .control:
            vc = UIHostingController(rootView: ControlPreview())
        case .button:
            vc = UIHostingController(rootView: ButtonPreview())
        case .iconButton:
            vc = UIHostingController(rootView: IconButtonPreview())
        case .chip:
            vc = UIHostingController(rootView: ChipPreview())
        case .contentBadge:
            vc = UIHostingController(rootView: ContentBadgePreview())
        case .pushBadge:
            vc = UIHostingController(rootView: PushBadgePreview())
        case .thumbnail:
            vc = ThumbnailPreviewBuilder().build()
        case .topNavigation:
            vc = UIHostingController(rootView: TopNavigationPreview())
        case .loading:
            vc = UIHostingController(rootView: LoadingPreview())
        case .progressIndicator:
            vc = UIHostingController(rootView: ProgressIndicatorPreview())
        case .avatar:
            vc = UIHostingController(rootView: AvatarPreview())
        case .skeleton:
            vc = UIHostingController(rootView: SkeletonPreview())
        case .emptyState:
            vc = UIHostingController(rootView: EmptyStatePreview())
        case .toast:
            vc = UIHostingController(rootView: ToastPreview())
        case .snackbar:
            vc = UIHostingController(rootView: SnackBarPreview())
        case .tooltip:
            vc = UIHostingController(rootView: TooltipPreview())
        case .actionArea:
            vc = UIHostingController(rootView: ActionAreaPreview())
        case .textArea:
            vc = UIHostingController(rootView: TextAreaPreview())
        case .textField:
            vc = UIHostingController(rootView: TextFieldPreview())
        case .select:
            vc = UIHostingController(rootView: SelectPreview())
        case .segmentedControl:
            vc = UIHostingController(rootView: SegmentedControlPreview())
        case .cell:
            vc = UIHostingController(rootView: CellPreview())
        case .tab:
            vc = UIHostingController(rootView: TabPreview())
        case .slider:
            vc = UIHostingController(rootView: SliderPreview())
        case .pullToRefresh:
            vc = UIHostingController(rootView: PullToRefreshPreview())
        case .progressTracker:
            vc = UIHostingController(rootView: ProgressTrackerPreview())
        case .dateTimePicker:
            vc = UIHostingController(rootView: DateTimePickerPreview())
        case .pagination:
            vc = UIHostingController(rootView: PaginationPreview())
        case .accordion:
            vc = UIHostingController(rootView: AccordionPreview())
        case .category:
            vc = UIHostingController(rootView: CategoryPreview())
        case .playIconBadge:
            vc = UIHostingController(rootView: PlayIconBadgePreview())
        case .sectionHeader:
            vc = UIHostingController(rootView: SectionHeaderPreview())
        case .menu:
            vc = UIHostingController(rootView: MenuPreview())
        case .modal:
            vc = UIHostingController(rootView: ModalPreview())
        case .flowLayout:
            vc = UIHostingController(rootView: FlowLayoutPreview())
        case .divider: fallthrough
        case .card:
            return
        }
        
        vc.navigationItem.title = itemType.title
        vc.navigationItem.largeTitleDisplayMode = .never
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
