//
//  ComponentListRouter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Montage
import SwiftUI

// MARK: - ComponentListRouter

final class ComponentListRouter: NSObject {
    weak var viewController: UIViewController?

    /// 자유롭게 다른 scene builder 추가하기 (Freely add builders of different scenes)
    init(viewController: UIViewController) {
        self.viewController = viewController
    }
}

// MARK: - ComponentListRoutingLogic

extension ComponentListRouter: ComponentListRoutingLogic {
    func routeToComponent(_ itemType: ComponentListContents.ComponentType) {
        let vc: UIViewController

        switch itemType {
        case .typography:
            vc = UIHostingController(rootView: TypographyPreview())
        case .color:
            vc = UIHostingController(rootView: ColorPreview())
        case .icon:
            vc = UIHostingController(rootView: IconPreview())
        case .shadow:
            vc = UIHostingController(rootView: ShadowPreview())
        case .control:
            vc = UIHostingController(rootView: ControlPreview())
        case .button:
            vc = UIHostingController(rootView: ButtonPreview())
        case .textButton:
            vc = UIHostingController(rootView: TextButtonPreview())
        case .iconButton:
            vc = UIHostingController(rootView: IconButtonPreview())
        case .chip:
            vc = UIHostingController(rootView: ChipPreview())
        case .contentBadge:
            vc = UIHostingController(rootView: ContentBadgePreview())
        case .pushBadge:
            vc = UIHostingController(rootView: PushBadgePreview())
        case .thumbnail:
            vc = UIHostingController(rootView: ThumbnailPreview())
        case .topNavigation:
            vc = UIHostingController(rootView: TopNavigationPreview())
        case .loading:
            vc = UIHostingController(rootView: LoadingPreview())
        case .progressIndicator:
            vc = UIHostingController(rootView: ProgressIndicatorPreview())
        case .avatar:
            vc = UIHostingController(rootView: AvatarPreview())
        case .skeleton:
            vc = UIHostingController(rootView: SkeletonPreview())
        case .fallbackView:
            vc = UIHostingController(rootView: FallbackViewPreview())
        case .toast:
            vc = UIHostingController(rootView: ToastPreview())
        case .snackbar:
            vc = UIHostingController(rootView: SnackBarPreview())
        case .tooltip:
            vc = UIHostingController(rootView: TooltipPreview())
        case .actionArea:
            vc = UIHostingController(rootView: ActionAreaPreview())
        case .textArea:
            vc = UIHostingController(rootView: TextAreaPreview())
        case .textField:
            vc = UIHostingController(rootView: TextFieldPreview())
        case .select:
            vc = UIHostingController(rootView: SelectPreview())
        case .segmentedControl:
            vc = UIHostingController(rootView: SegmentedControlPreview())
        case .listCell:
            vc = UIHostingController(rootView: ListCellPreview())
        case .tab:
            vc = UIHostingController(rootView: TabPreview())
        case .slider:
            vc = UIHostingController(rootView: SliderPreview())
        case .pullToRefresh:
            vc = UIHostingController(rootView: PullToRefreshPreview())
        case .progressTracker:
            vc = UIHostingController(rootView: ProgressTrackerPreview())
        case .dateTimePicker:
            vc = UIHostingController(rootView: DateTimePickerPreview())
        case .pagination:
            vc = UIHostingController(rootView: PaginationPreview())
        case .accordion:
            vc = UIHostingController(rootView: AccordionPreview())
        case .category:
            vc = UIHostingController(rootView: CategoryPreview())
        case .playBadge:
            vc = UIHostingController(rootView: PlayBadgePreview())
        case .sectionHeader:
            vc = UIHostingController(rootView: SectionHeaderPreview())
        case .modal:
            vc = UIHostingController(rootView: ModalPreview())
        case .flowLayout:
            vc = UIHostingController(rootView: FlowLayoutPreview())
        case .card:
            vc = UIHostingController(rootView: CardPreview())
        case .listCard:
            vc = UIHostingController(rootView: ListCardPreview())
        case .framedStyle:
            vc = UIHostingController(rootView: FramedStylePreview())
        case .divider:
            return
        }

        vc.navigationItem.title = itemType.title
        vc.navigationItem.largeTitleDisplayMode = .never
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
