//
//  ComponentListModels.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ComponentList {
    typealias Contents = ComponentListContents
    
    enum Response {
        case contents(_ contents: Contents)
    }
    
    enum ViewModel {
        struct Components {
            let categories: [Category]
        }
        
        struct Category {
            let type: String
            let items: [Item]
        }
        
        struct Item: Hashable {
            let id = UUID()
            let name: String
            let color: UIColor
            let font: UIFont
            
            func hash(into hasher: inout Hasher) {
                hasher.combine(id)
            }
        }
    }
}
