//
//  ComponentListPresenter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/02.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

// MARK: - ComponentListPresenter

final class ComponentListPresenter {
    weak var viewController: ComponentListDisplayLogic?
}

// MARK: - ComponentListPresentationLogic

extension ComponentListPresenter: ComponentListPresentationLogic {
    func presentItems(_ items: [ComponentListContents.CategoryItemSet]) {
        viewController?.display(ComponentList.ViewModel.Components(
            categories: items.map({
                .init(
                    type: $0.category.title,
                    items: $0.items.map { item in
                            .init(
                                name: item.title,
                                color: getItemStateColor(item.state),
                                font: getItemStateFont(item.state) ?? .systemFont(ofSize: 14)
                            )
                    }
                )
            }))
        )
    }
}

extension ComponentListPresenter {
    private func getItemStateColor(_ state: ComponentState) -> UIColor {
        switch state {
        case .pending:
            return .semantic(.labelDisable)
        case .previewNotReady:
            return .semantic(.statusCautionary)
        case .completed:
            return .semantic(.statusPositive)
        }
    }
    
    private func getItemStateFont(_ state: ComponentState) -> UIFont? {
        switch state {
        case .pending:
            return .font(variant: .body2, weight: .regular)
        case .previewNotReady:
            return .font(variant: .body1, weight: .regular)
        case .completed:
            return .font(variant: .body1, weight: .bold)
        }
    }
}

// MARK: - ComponentListDisplayLogic definition

protocol ComponentListDisplayLogic: AnyObject {
    func display(_ viewModel: ComponentList.ViewModel.Components)
}
