name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
          
      - name: Remove DerivedData
        run: |
          rm -rf ./DerivedData

      - name: Build
        run: |
          xcodebuild clean build \
            -scheme Montage \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
            -derivedDataPath "./DerivedData" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify;
