name: Labeler

on:
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    if: github.event.pull_request.head.repo.full_name == github.repository
    timeout-minutes: 3
    runs-on: [self-hosted, utility]
    steps:
      - uses: jsryudev/pr-review-labeler@v0.2.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          target-approved-count: 1
          label-to-be-added: "accepted"
          label-to-be-removed: "in review"
