//
//  IconViewController.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/27.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

// MARK: - IconPreviewController

final class IconPreviewController: BaseViewController {
    typealias Item = IconPreview.ViewModel.Item
    typealias DataSource = UICollectionViewDiffableDataSource<String, Item>
    typealias Snapshot = NSDiffableDataSourceSnapshot<String, Item>
    
    private lazy var collectionView: UICollectionView = {
        var config = UICollectionLayoutListConfiguration(appearance: .plain)
        config.showsSeparators = false
        config.backgroundColor = .semantic(.backgroundNormal)
        let layout = UICollectionViewCompositionalLayout.list(using: config)
        return UICollectionView(frame: view.bounds, collectionViewLayout: layout)
    }()
    
    private lazy var hSpacingItem = UIButton(configuration: .plain())
    
    private lazy var vSpacingItem = UIButton(configuration: .plain())
    
    lazy var dataSource: DataSource = makeDataSource()
    var interactor: IconPreviewRequestLogic?

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        
        interactor?.process(IconPreview.Request.OnLoad())
    }
}

extension IconPreviewController {
    private func setupViews() {
        title = "Icon & Grid"
        
        setupNavigationItem()
        setupCollectionView()
    }
    
    private func setupCollectionView() {
        view.addSubview(collectionView)
        setContentScrollView(collectionView)
        
        collectionView.backgroundColor = .clear
        collectionView.register(IconPreviewCell.self)
        
        collectionView.snp.makeConstraints {
            $0.top.left.right.equalTo(view.safeAreaLayoutGuide)
            $0.bottom.equalToSuperview()
        }
    }
    
    private func setupNavigationItem() {
        let itemStackView = UIStackView()
        itemStackView.axis = .horizontal
        
        itemStackView.addArrangedSubview(vSpacingItem)
        itemStackView.addArrangedSubview(hSpacingItem)
        
        navigationItem.rightBarButtonItem = .init(customView: itemStackView)
    }
}

extension IconPreviewController {
    private func makeDataSource() -> DataSource {
        return .init(collectionView: collectionView) { collectionView, indexPath, item in
            let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as IconPreviewCell
            cell.configure(with: item)
            return cell
        }
    }
}

// MARK: - IconPreviewDisplayLogic

extension IconPreviewController: IconPreviewDisplayLogic {
    func display(_ viewModel: IconPreview.ViewModel.List) {
        var snapshot = dataSource.snapshot()
        snapshot.deleteAllItems()
        snapshot.appendSections(["Icons"])
        snapshot.appendItems(viewModel.items)
        dataSource.apply(snapshot, animatingDifferences: true)
    }
    
    func display(_ viewModel: IconPreview.ViewModel.HSpacingSelector) {
        let actions = viewModel.items.enumerated().map { index, item in
            UIAction(
                title: item.title,
                state: item.isSelected ? .on : .off
            ) { [self] _ in
                self.interactor?.process(IconPreview.Request.OnSelectHSpacingSize(index: index))
            }
        }
        
        hSpacingItem.menu = UIMenu(children: actions)
        hSpacingItem.setImage(.init(systemName: "arrow.left.and.right"), for: .normal)
        hSpacingItem.showsMenuAsPrimaryAction = true
    }
    
    func display(_ viewModel: IconPreview.ViewModel.VSpacingSelector) {
        let actions = viewModel.items.enumerated().map { index, item in
            UIAction(
                title: item.title,
                state: item.isSelected ? .on : .off
            ) { [self] _ in
                self.interactor?.process(IconPreview.Request.OnSelectVSpacingSize(index: index))
            }
        }
        
        vSpacingItem.menu = UIMenu(children: actions)
        vSpacingItem.setImage(.init(systemName: "arrow.up.and.down.square"), for: .normal)
        vSpacingItem.showsMenuAsPrimaryAction = true
    }
}
