//
//  IconPreviewRouter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/27.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - IconPreviewRouter

final class IconPreviewRouter: NSObject {
    weak var viewController: UIViewController?
    
    /// 자유롭게 다른 scene builder 추가하기 (Freely add builders of different scenes)
    init(viewController: UIViewController) {
        self.viewController = viewController
    }
}

// MARK: - IconRoutingLogic

extension IconPreviewRouter: IconPreviewRoutingLogic {
    
    func routeToSomewhere() {
        
    }
}
