//
//  IconPreviewModels.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/27.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

enum IconPreview {

    enum Request {
        struct OnLoad {}
        
        struct OnSelectHSpacingSize {
            let index: Int
        }
        
        struct OnSelectVSpacingSize {
            let index: Int
        }
    }
    
    enum Response: Equatable {
        case iconList(_ hSpacing: Spacing, _ vSpacing: Spacing)
        case hSpacingMenu(_ all: [Spacing], _ current: Spacing)
        case vSpacingMenu(_ all: [Spacing], _ current: Spacing)
    }
    
    enum ViewModel {
        struct List {
            let items: [Item]
        }
        
        struct Item: Hashable {
            let id = UUID()
            let icon: Icon
            let appearance: Appearance
            
            func hash(into hasher: inout Hasher) {
                hasher.combine(id)
            }
        }
        
        struct Appearance: Equatable {
            let iconInset: CGFloat
            let titleSpacing: CGFloat
        }
        
        struct SelectorOption {
            let title: String
            let isSelected: Bool
        }
        
        struct HSpacingSelector {
            let items: [SelectorOption]
        }
        
        struct VSpacingSelector {
            let items: [SelectorOption]
        }
    }
}
