//
//  IconPreviewInteractor.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/27.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Montage

// MARK: - IconPreviewInteractor

final class IconPreviewInteractor {
    var presenter: IconPreviewPresentationLogic?
    var router: IconPreviewRoutingLogic?
    private let worker: IconPreviewWorkingLogic
    
    private var allSpacing: [Spacing] = [
        .pt01, .pt02, .pt04, .pt08, .pt12, .pt16, .pt20, .pt24, .pt28,
        .pt32, .pt36, .pt40, .pt48, .pt56, .pt64, .pt72, .pt80
    ]
    
    private var selectedHSpacing: Spacing = .pt12
    private var selectedVSpacing: Spacing = .pt08

    init(worker: IconPreviewWorkingLogic) {
        self.worker = worker
    }
}

// MARK: - IconRequestLogic

extension IconPreviewInteractor: IconPreviewRequestLogic {
    func process(_ request: IconPreview.Request.OnLoad) {
        presenter?.present(.iconList(selectedHSpacing, selectedVSpacing))
        presenter?.present(.hSpacingMenu(allSpacing, selectedHSpacing))
        presenter?.present(.vSpacingMenu(allSpacing, selectedVSpacing))
    }
    
    func process(_ request: IconPreview.Request.OnSelectHSpacingSize) {
        guard let selectedSize = allSpacing[safe: request.index] else {
            return
        }
        
        selectedHSpacing = selectedSize
        presenter?.present(.hSpacingMenu(allSpacing, selectedSize))
        presenter?.present(.iconList(selectedHSpacing, selectedVSpacing))
    }
    
    func process(_ request: IconPreview.Request.OnSelectVSpacingSize) {
        guard let selectedSize = allSpacing[safe: request.index] else {
            return
        }
        
        selectedVSpacing = selectedSize
        presenter?.present(.vSpacingMenu(allSpacing, selectedSize))
        presenter?.present(.iconList(selectedHSpacing, selectedVSpacing))
    }
}

// MARK: - IconRequestLogic definition

protocol IconPreviewRequestLogic {
    func process(_ request: IconPreview.Request.OnLoad)
    func process(_ request: IconPreview.Request.OnSelectHSpacingSize)
    func process(_ request: IconPreview.Request.OnSelectVSpacingSize)
}

// MARK: - IconWorkingLogic definition

protocol IconPreviewWorkingLogic {}

// MARK: - IconPresentationLogic definition

protocol IconPreviewPresentationLogic {
    func present(_ response: IconPreview.Response)
}

// MARK: - IconRoutingLogic definition

protocol IconPreviewRoutingLogic {}

