//
//  IconPreviewPresenter.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/27.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Montage

// MARK: - IconPreviewPresenter

final class IconPreviewPresenter {
    weak var viewController: IconPreviewDisplayLogic?
}

// MARK: - IconPresentationLogic

extension IconPreviewPresenter: IconPreviewPresentationLogic {
    func present(_ response: IconPreview.Response) {
        switch response {
        case .iconList(let hSpacing, let vSpacing):
            viewController?.display(
                IconPreview.ViewModel.List(
                    items: Icon.allCases.map {
                        .init(
                            icon: $0,
                            appearance: .init(
                                iconInset: .spacing(vSpacing),
                                titleSpacing: .spacing(hSpacing)
                            )
                        )
                    }
                )
            )
        case .hSpacingMenu(let allItem, let selectedItem):
            viewController?.display(
                IconPreview.ViewModel.HSpacingSelector(
                    items: allItem.map {
                        .init(title: String(describing: $0), isSelected: $0 == selectedItem)
                    }
                )
            )
        case .vSpacingMenu(let allItem, let selectedItem):
            viewController?.display(
                IconPreview.ViewModel.VSpacingSelector(
                    items: allItem.map {
                        .init(title: String(describing: $0), isSelected: $0 == selectedItem)
                    }
                )
            )
        }
    }
}

// MARK: - IconDisplayLogic definition

protocol IconPreviewDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: IconPreview.ViewModel.List)
    func display(_ viewModel: IconPreview.ViewModel.HSpacingSelector)
    func display(_ viewModel: IconPreview.ViewModel.VSpacingSelector)
}
