//
//  IconPreviewBuilder.swift
//  Blueprint
//
//  Created by Euigyom Kim on 2023/01/27.
//  Copyright (c) 2023 WantedLab Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - IconPreviewBuilder

final class IconPreviewBuilder {

}

// MARK: - IconPreviewBuildingLogic

extension IconPreviewBuilder: IconPreviewBuildingLogic {
    
    func build() -> Destination {
        let viewController = IconPreviewController()
        let interactor = IconPreviewInteractor(worker: IconPreviewWorker())
        let presenter = IconPreviewPresenter()
        let router = IconPreviewRouter(viewController: viewController)
        viewController.interactor = interactor
        interactor.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - IconBuildingLogic definition

protocol IconPreviewBuildingLogic {
    typealias Destination = IconPreviewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build() -> Destination
}
